### ISSUE TITLE
Provider works fine in Emulator but not on real device

### ISSUE THREAD

**Issue by TheGadri** [rrousselGit/provider#381] opened 2020-03-11 16:07 UTC
Hello, I have followed the documentation and implemented the steps in my app. I used the [Modal Progress Hud package](https://pub.dev/packages/modal_progress_hud) 'Ill be referring to it as MPH', where I show the MPH by using a boolean(true to show the MPH, false for otherwise). I update the state of the MPH using the provider package and changenotifier. It works fine in emulator but not on real device. Real device keeps on show the MPH.

`var model = Provider.of<Service>(context);`

![Screenshot (43)](https://user-images.githubusercontent.com/40185831/76436485-3272ce00-63b0-11ea-9f44-46b915643c83.png)
![image](https://user-images.githubusercontent.com/40185831/76436891-b1680680-63b0-11ea-8a5a-9c793962d014.png)
![image](https://user-images.githubusercontent.com/40185831/76437201-1ae81500-63b1-11ea-8563-c99deb036f6d.png)
![image](https://user-images.githubusercontent.com/40185831/76437563-a3ff4c00-63b1-11ea-923d-8e54ec7edb5f.png)

Please help

**Comment by rrousselGit** [comment] 2020-04-11 09:38
Please provide a minimal code sample to reproduce the problem. Otherwise I cannot help you

**Comment by rrousselGit** [comment] 2020-06-04 23:45
Closing this as I cannot reproduce the problem. Feel free to make a new issue with more information if you still have the problem.

**Closed by rrousselGit** 2020-06-04 23:45 UTC
Labels: question
