### ISSUE TITLE
Doc error?  Shouldn't a Consumer2<A,B> consume a Provider2<A,B>, not a Provider<T>

### ISSUE THREAD

**Issue by RandalSchwartz** [rrousselGit/provider#127] opened 2019-06-22 18:29 UTC

**Comment by rrousselGit** [comment] 2019-06-22 18:32
Hello,

I do not understand what you mean by this

**Comment by peekpt** [comment] 2019-06-28 15:55
@RandalSchwartz No, because Provider can be inserted anywhere in the widget tree and you don't necessary insert 2 Providers in the same place. But If you need to you have Multiprovider widget. Also there's a few different providers.

**Comment by rrousselGit** [comment] 2019-07-03 15:56
I still don't understand what this is about.

In the lack of an explanation I'll close it.

**Closed by rrousselGit** 2019-07-03 15:56 UTC
Labels: documentation, question

**Comment by MaikuB** [comment] 2019-07-05 23:43
I believe the question here is related to semantics and API design. When trying to build a model of how the provider package works, one way to think of it is that a `Provider` widget is paired with a `Consumer` widget (i.e. they're opposites). Based on that understanding, if one saw a `Consumer2` widget, they'd likely expect that there's a `Provider2` widget. However, that's not actually the case

**Comment by peekpt** [comment] 2019-07-06 09:15
Consumer2 takes two providers , Consumer3 takes three , and so on... Simple

A sábado, 6/07/2019, 00:43, Michael Bui <notifications@github.com> escreveu:

**Comment by MaikuB** [comment] 2019-07-06 09:37
@peekpt thanks, I'm aware of how those widgets work. Just trying to help explain to @rrousselGit what I believe to be the reason why @RandalSchwartz asked the question.

**Comment by MaikuB** [comment] 2019-07-06 09:52
I guess this does raise an interesting question that if `MultiProvider` provides multiple values, perhaps renaming the `Consumer2`, `Consumer3` etc widgets to `MultiConsumer` to express that it's to consume multiple values. Just a thought

**Comment by peekpt** [comment] 2019-07-06 21:21
The problem is that you need you need Generics 
Consumer<T,B,G>(....

**Comment by rrousselGit** [comment] 2019-07-06 21:25
> I guess this does raise an interesting question that if MultiProvider provides multiple values, perhaps renaming the Consumer2, Consumer3 etc widgets to MultiConsumer would help better express that it's to consume multiple values. Just a thought

I disagree.

`MultiProvider` stands on its own and has nothing to do with `Provider` or similar widgets.

On the other hand, `Consumer` [...] `Consumer6` are a copy-paste of the same code with an extra argument. 
They are separated only because of the typing system.

**Comment by MaikuB** [comment] 2019-07-06 23:35
@rrousselGit: I'm not saying `MultiProvider` does have anything to do with the other widgets but yeah wasn't aware Dart wouldn't allow defining multiple classes of the same name but with different number of types i.e. it doesn't allow you have `Consumer<T>`,` Consumer<T1, T2>`. That's a shame, perhaps something that could come in future versions of Dart

**Comment by peekpt** [comment] 2019-07-07 09:04
You can use an abstract class and implement it into your classes, but then you have to test the type on the runtime
