### ISSUE TITLE
Consumer Not Getting Notified Despite notifyListeners()

### ISSUE THREAD

**Issue by psygo** [rrousselGit/provider#393] opened 2020-03-24 00:23 UTC
## The Problem

> I have posted about this problem [in this SO question](https://stackoverflow.com/q/60764218/4756173). You can check out the complete code [here](https://github.com/psygo/flutter_firebase_auth_benchmark).

I'm not 100% sure of what's going on in my app, but somehow, one of my providers notifies its listeners and, still nothing changes.

My current project is a basic authentication app with Firebase. The Firebase errors only appear after the user clicks on a button, and the main difference that's causing me problems is that I'm showing the error messages on the `labelText`. The submit button calls the `save()` method on the `Form`, but, if I call it synchronously, initially, nothing changes, despite the `notifyListeners()` having been triggered (in an `await`ed `Future`). I have to click the button twice, i.e, save twice for the `labelText` to change.

However, if I wrap the saving in a delayed future, everything works fine for some reason:

```dart
Future<void> save() async => 
    await Future.delayed(Duration(milliseconds: 100), () {
      _formKey.currentState.save();
    });
```

## What I think is going on

At first, I thought that, since two providers are used in the action button &mdash; one for handling the `Form` and another for the authentication data &mdash; maybe they were sending conflicting notificaitons and the `Form` was being improperly updated. But now I'm thinking that it might be related to the fact that I'm updating the `formKey` in the `didChangeDependencies()` method.

Has anyone had a similar problem of misupdating a `Form`? Am I using the wrong type of provider? Does anyone have a clue of what's going on?

## The Structure of the App

I think most of what's going might be coming from the architecture of the project, even though I still don't know why this problem is happening. The complexity of the code rose quite considerably once I decided to introduce animations. Anyway, here's how it's organized &mdash; check out the complete code [here](https://github.com/psygo/flutter_firebase_auth_benchmark) &mdash;:

- `LoginScreen`: has the email and password fields, and also has an `AnimatedSwitcher` which has each of the subworkflows for signing in, signing up and password resetting.
- The buttons in the different workflows the `AnimatedSwitcher` switches to will operate on the `LoginWorkflowProvider`, which will update the `Form` and also occasionally update the data in the `Auth` provider.
    - For example, when password resetting, if the user doesn't exist, `auth.emailErrorMsg` will be updated, `notifyListeners()` will be called, and the `Consumer<Auth>` above the email field will/should guarantee the field is rebuilt.

**Comment by rrousselGit** [comment] 2020-06-04 23:44
Considering the issue is old and without answer, I'll close this for now.

If you still have problem, feel free to say so!

**Closed by rrousselGit** 2020-06-04 23:44 UTC
