### ISSUE TITLE
Flutter Provider Error: The following ProviderNotFoundException was thrown building HomePage(dirty, state: flutter: _HomePageState#fb424):

### ISSUE THREAD

**Issue by shehriyarmalik** [rrousselGit/provider#546] opened 2020-10-05 10:39 UTC
My code was actually working and is currently working with the app built from the previous version of flutter. I built it again using the same code but with the Flutter 1.22 upgrade and its causing error now on Provider. Since, the code actually worked, I can't seem to figure out why it is throwing an error. 

Here is my code: 

The file or the error causing widget according to flutter: 
'''
```
class HomePage extends StatefulWidget {
  static final String id = 'home_page';
  final String currentUserId;
  HomePage({this.currentUserId});
  @override
  _HomePageState createState() => _HomePageState();
}

CategoryProvider categoryProvider;
ProductProvider productProvider;

class _HomePageState extends State<HomePage> {

  final GlobalKey<ScaffoldState> _key = GlobalKey<ScaffoldState>();

  void getCallAllFunction() {
    categoryProvider.getWaxData();
    categoryProvider.getHairData();
    categoryProvider.getPedicureData();
    categoryProvider.getManicureData();
    categoryProvider.getFacialData();
    categoryProvider.getHairIconData();
    productProvider.getNewAchiveData();
    productProvider.getFeatureData();
    productProvider.getHomeFeatureData();
    productProvider.getHomeAchiveData();
    categoryProvider.getWaxIcon();
    categoryProvider.getPedicureIconData();
    categoryProvider.getManicureIconData();
    categoryProvider.getFacialIconData();
  
  }

  @override
  Widget build(BuildContext context) {

    categoryProvider = Provider.of<CategoryProvider>(context);
    productProvider = Provider.of<ProductProvider>(context);
    final String currentUserId = Provider.of<UserData>(context).currentUserId;
    getCallAllFunction();
    height = MediaQuery.of(context).size.height;
    width = MediaQuery.of(context).size.width;

    return Scaffold(
      key: _key,
      drawer: _buildMyDrawer(),
      appBar: AppBar(
        toolbarOpacity: 0,
        shape: RoundedRectangleBorder(),
        // search field
        title: Text(
          'Home',
          style: TextStyle(
            color: Colors.white,
            fontFamily: 'Billabong',
            fontSize: 35.0,
          ),
        ),
        elevation: 0.0,
        backgroundColor: Colors.blueGrey,
        leading: IconButton(
          icon: SvgPicture.asset("images/menu.svg"),
          onPressed: () {
            
          },
        ),
      ),
      body: Container(
        height: double.infinity,
        width: double.infinity,
        margin: EdgeInsets.symmetric(horizontal: 20),
        child: ListView(
          scrollDirection: Axis.vertical,
          children: <Widget>[
            
        
          ],
        ),
      ),
    );
  }
}
```
'''

I have provided the multi providers in the main while with child as MaterialApp. Hence the main file looks like this: 

'''

 ```
   void main() async {
      WidgetsFlutterBinding.ensureInitialized();
      await Firebase.initializeApp();
      runApp(
        MultiProvider(
          providers: [
            ChangeNotifierProvider(
              create: (context) => ServicesNotifier(),
            ),
            ChangeNotifierProvider(
              create: (context) => HairdresserData(),
            ),
            ChangeNotifierProvider(
              create: (context) => ServicesNotifier(),
            ),
            ChangeNotifierProvider<CategoryProvider>(
              create: (context) => CategoryProvider(),
            ),
            ChangeNotifierProvider<ProductProvider>(
              create: (context) => ProductProvider(),
            ),
            ChangeNotifierProvider(
              create: (context) => UserData(),
            ),
          ],
          child: MyApp(),
        ),
      );
    }
    '''
    class MyApp extends StatelessWidget {
      // This widget is the root of your application.
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          home: OnboardingScreen(),
          routes: {
            //  '/a': (_) => Authenticate(),
            SignInScreen.id: (context) => SignInScreen(),
            RegisterScreen.id: (context) => RegisterScreen(),
            LoginScreen.id: (context) => LoginScreen(),
            SignupScreen.id: (context) => SignupScreen(),
            '/b': (_) => Customer(),
            '/c': (_) => Hairdresser(),
            '/d': (_) => Choose(),
            '/e': (_) => IndicatorScreen(),
          },
        );
      }
    }
```

The error is as follows: 

'''
The following ProviderNotFoundException was thrown building HomePage(dirty, state:
flutter: _HomePageState#fb424):
flutter: Error: Could not find the correct Provider<CategoryProvider> above this HomePage Widget
flutter:
flutter: This likely happens because you used a `BuildContext` that does not include the provider
flutter: of your choice. There are a few common scenarios:
flutter:
flutter: - The provider you are trying to read is in a different route.
flutter:
flutter:   Providers are "scoped". So if you insert of provider inside a route, then
flutter:   other routes will not be able to access that provider.
flutter:
flutter: - You used a `BuildContext` that is an ancestor of the provider you are trying to read.
flutter:
flutter:   Make sure that HomePage is under your MultiProvider/Provider<CategoryProvider>.
flutter:   This usually happen when you are creating a provider and trying to read it immediately.
flutter:
flutter:   For example, instead of:
flutter:
flutter:   ```
flutter:   Widget build(BuildContext context) {
flutter:     return Provider<Example>(
flutter:       create: (_) => Example(),
flutter:       // Will throw a ProviderNotFoundError, because `context` is associated
flutter:       // to the widget that is the parent of `Provider<Example>`
flutter:       child: Text(context.watch<Example>()),
flutter:     ),
flutter:   }
flutter:   ```
flutter:
flutter:   consider using `builder` like so:
flutter:   ```
flutter:   Widget build(BuildContext context) {
flutter:     return Provider<Example>(
flutter:       create: (_) => Example(),
flutter:       // we use `builder` to obtain a new `BuildContext` that has access to the provider
flutter:       builder: (context) {
flutter:         // No longer throws
flutter:         return Text(context.watch<Example>()),
flutter:       }
flutter:     ),
flutter:   }
flutter:   ```

Edit: 
So I edited the code. Basically the problem is coming from initiating the providers as you can see in the HomePage. 

```
CategoryProvider` categoryprovider; 

Widget build(BuildContext context) {

    categoryProvider = Provider.of<CategoryProvider>(context);

```
Basically this is throwing the error for some reason. 

then the error is as follows: 

```
This likely happens because you used a BuildContext that does not include the provider
flutter: of your choice. There are a few common scenarios:
flutter:
flutter: - The provider you are trying to read is in a different route.
flutter:
flutter: Providers are "scoped". So if you insert of provider inside a route, then
flutter: other routes will not be able to access that provider.
flutter:
flutter: - You used a BuildContext that is an ancestor of the provider you are trying to read.
flutter:
flutter: Make sure that HomePage is under your MultiProvider/Provider.
flutter: This usually happen when you are creating a provider and trying to read it immediately.
```

I don't understand why when Its provider is already in the main.dart file.
And also like I mentioned, it is working on my previous project which was built with in flutter 1.20 however not working with the updated/latest version for some reason. 
 Kindly help.

**Comment by rrousselGit** [comment] 2020-10-05 11:17
Hello!

There is too much code. Could you strip down your snippet such that it can be both executed and involves as little code as possible, with clear steps to reproduce the issue?

**Comment by shehriyarmalik** [comment] 2020-10-05 12:03
So I edited the code. Basically the problem is coming from initiating the providers as you can see in the HomePage. 

```
CategoryProvider` categoryprovider; 

Widget build(BuildContext context) {

    categoryProvider = Provider.of<CategoryProvider>(context);

```
Basically this is throwing the error for some reason. 

then the error is as follows: 

```
This likely happens because you used a BuildContext that does not include the provider
flutter: of your choice. There are a few common scenarios:
flutter:
flutter: - The provider you are trying to read is in a different route.
flutter:
flutter: Providers are "scoped". So if you insert of provider inside a route, then
flutter: other routes will not be able to access that provider.
flutter:
flutter: - You used a BuildContext that is an ancestor of the provider you are trying to read.
flutter:
flutter: Make sure that HomePage is under your MultiProvider/Provider.
flutter: This usually happen when you are creating a provider and trying to read it immediately.
```


I don't understand why when Its provider is already in the main.dart file.
And also like I mentioned, it is working on my previous project which was built with in flutter 1.20 however not working with the updated/latest version for some reason. 
 Kindly help.

**Comment by shehriyarmalik** [comment] 2020-10-05 12:50
Secondly the providers are retrieving data from firebase. Hence if you want to execute the code you would need access or basically all the files. Anyways that being said, maybe i need to use a future builder or something to retrieve data then? Because its on firebase?

**Comment by rrousselGit** [comment] 2020-10-05 12:52
I don't see a HomePage widget in your MyApp

In any case, as I mentioned previously, please make small project that can be executed, with just enough code to reproduce the issue.

**Comment by rrousselGit** [comment] 2020-12-11 17:07
I'll close this in the lack of a reply

**Closed by rrousselGit** 2020-12-11 17:07 UTC
Labels: question

**Comment by Haseeb-Akhlaq** [comment] 2020-12-29 14:53
I have the same issue not resolving

**Comment by dev12ts12** [comment] 2021-01-04 06:01
I simply resolve this issue by move all the files to lib instead of making provider directory to lib because provider did not able to file another file that we want to use.

**Comment by Haseeb-Akhlaq** [comment] 2021-01-04 06:04
Yeah I got this solved by creating a new file with name changed and moved all code from pervious file to it and it worked smoothly

**Comment by Algure** [comment] 2021-04-03 21:40
Had the exact same issue. It turned out  that I was importing the provider from the file tree and not the package.

I was doing this:

```import '../promo_model.dart';
```
Instead of this.

```import 'package:gmartapp/promo_model.dart';
```
Just make sure your provider is imported from your app package not your file tree.

**Comment by mrudulmohan007** [comment] 2023-10-31 15:15
> I simply resolve this issue by move all the files to lib instead of making provider directory to lib because provider did not able to file another file that we want to use.

can u elaborate more?

**Comment by Angeloem** [comment] 2024-07-13 21:42
> Had the exact same issue. It turned out that I was importing the provider from the file tree and not the package.

I think the dart tool has an issue with auto imports. The providers were in a folder with AaaaaBbbb casing, the auto import would auto import it as aaaaaBbbb. and that would lead to problems
