### ISSUE TITLE
`ProxyProvider.update` Should Not Be Executed on Init When `create` Exists

### ISSUE THREAD

**Issue by SupposedlySam** [rrousselGit/provider#519] opened 2020-08-20 22:41 UTC
**Describe the bug**
When using a `ProxyProvider` with both the `create` and `update` functions supplied, then I expect the `update` method to not be called until the value we're listening to updates.

Expected:
Run app, listen to proxy provider, create method called.
Update dependency of proxy provider, update method is called.

Actual:
Run app, listen to proxy provider, create AND update method called.

**To Reproduce**

```dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() {
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider<ValueNotifier<bool>>(
            create: (_) => ValueNotifier(false)),
        ProxyProvider<ValueNotifier<bool>, String>(
          create: (context) {
            print('create called');
            final notifier = Provider.of<ValueNotifier<bool>>(
              context,
              listen: false,
            );
            return 'The value is: ${notifier.value}';
          },
          update: (_, notifier, value) {
            print('update called');
            return 'The updated value is: ${notifier.value}';
          },
        ),
      ],
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Material(
        child: Padding(
          padding: const EdgeInsets.all(15.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Text(context.watch<String>()),
              RaisedButton(
                onPressed: () {
                  final notifier = context.read<ValueNotifier<bool>>();
                  notifier.value = !notifier.value;
                },
                child: Text('Update Me'),
              )
            ],
          ),
        ),
      ),
    );
  }
}

```

**Expected behavior**
The text should only change from "the value is:..." to "the updated value is:..." when the dependency changes (via the button in this example).

**Suggestion**
As to not break current implementations it would be great if you add some kind of flag (similar to what you did with the `lazy` flag) so our team can toggle this lifecycle enhancement (or a bug to us) on/off.

**Additional Credit**
S/O to @agpiermarini for helping to uncover this behavior

**Comment by rrousselGit** [comment] 2020-08-20 23:09
This is the expected behavior. What is the motivation behind this change?

**Comment by SupposedlySam** [comment] 2020-08-24 16:27
> Could you verify before making the call that the parameters haven't changed?

We could definitely do that, and it's not a bad idea to go ahead and do that check before making the api call. However, that's a lot of extra state to keep around through our entire application since we'd need to cache the previously requested params. 

You mentioned that this was expected behavior. Would you mind detailing the reason behind this behavior being expected? 

I understand needing the update method to be called when the Provider is initialized since you can use the update method without the create method being populated. When the create method is also populated though, it seems like you'd want to just run the create method and only run update when dependencies change.

**Comment by rrousselGit** [comment] 2020-08-24 16:52
To be honest, I don't like ProxyProviders for numerous reasons. I think making them was a mistake.
An alternative is to use only create, and use addListeners to listen to updates on an object.

But to answer your question, the general goal is to have "create" only instantiate the object, and "update" take care of all the side effects related to external values

**Comment by SupposedlySam** [comment] 2020-08-28 19:23
Okay, thanks for you time. I believe we're going to do a refactor to remove ProxyProviders and just add and remove listeners where we need them.

If you have the time and appetite for the enhancement though, I do think it would be a nice improvement.

**Comment by gustav3d** [comment] 2020-09-24 07:03
Any progress ? :)

**Comment by rrousselGit** [comment] 2020-09-24 09:01
No

That's a big breaking change (or requires new flags, which is confusing)

**Comment by rrousselGit** [comment] 2021-09-24 11:40
Hey!
I will close this, since I don't think there's a way to implement this without a significant breaking change, and I'm not certain about its value.

**Closed by rrousselGit** 2021-09-24 11:40 UTC
Labels: enhancement
