### ISSUE TITLE
Strange behaviour from Provider

### ISSUE THREAD

**Issue by mcsugaman** [rrousselGit/provider#250] opened 2019-10-24 09:52 UTC
Hi,

I am just learning flutter and I used Provider to manage state in my application.
I have very strange problem:

When I run application on Emulator, it works perfectly. Widgets are refreshed every time, when I change any value in my provider class. It also works, when I run application with "flutter run" command on my Samsung S9 device.
But, when I build the .apk file and transfer it to my Samsung S9 and then install it, It doesn't work. Widgets just don't get refreshed when I change values in my Provider class. They only get changed values from Provider class, when I change the Widget using Navigator.push (routing).
What could be wrong here? 
I tried to clean and rebuild the project, but It doesn't work. 
It just doesn't make sense to my, that application is working on Emulator and on device whiel debugging, but It doesn't work when I build the .apk file using "flutter build apk" command.

Any suggestions?
Thanks.

**Comment by rrousselGit** [comment] 2019-10-31 23:43
Hello!

Could you make a minimalist repository to reproduce the error?

**Comment by rrousselGit** [comment] 2019-11-10 21:23
Closing this since there's no answer

Feel free to comment if you're still struggling with that 😄

**Closed by rrousselGit** 2019-11-10 21:23 UTC
Labels: question

**Comment by nmhernandez10** [comment] 2020-02-15 21:58
I have the same problem. Help. I used many providers with MultiProvider. All of them works perfectly on debug mode, but when I build an APK, just some work good, the others don't notify correctly to listeners so they dont rebuild widgets :(
