### ISSUE TITLE
NotifyListener() not working in release build (android)

### ISSUE THREAD

**Issue by KhanjanElsner** [rrousselGit/provider#763] opened 2022-07-04 12:18 UTC
I am using latest version of provider but in my project notifyListener() is working fine in debug mode but When I try to check same code in release mode then notifyListener() is not working and no action performing. I also used consumer but not updating the widget in release mode.

please resolve the issue as soon as possible

**Comment by rrousselGit** [comment] 2022-07-04 13:37
Please provide enough code to reproduce the problem.

**Comment by 1351438** [comment] 2022-07-18 08:12
Same issue.

**Comment by bazl-E** [comment] 2022-07-28 09:40
same issue

**Comment by rrousselGit** [comment] 2022-07-28 09:54
Please, for the love of gods, stop commenting "same issue".

Like I said, I need a way to reproduce the problem. If you don't give me a way to reproduce the problem, it's impossible for me to help you.

The only thing this kind of comment does is frustrate me.

**Comment by bazl-E** [comment] 2022-07-28 10:59
void removeSelectedAccount(SelectedAccount value, double walletBalance) {
    try {
      print("removeSelectedAccount");
      _selectdAccounts
          .removeWhere((element) => element.accountName == value.accountName);
      print("removeSelectedAccount");
      settotalAmountCollected(walletBalance);
    } catch (e) {
      toast("Error: $e");
    }
  }
 void settotalAmountCollected(double walletBalance) {
    try {
      print("settotalAmountCollected");
      if (_selectdAccounts.isEmpty) {
        _totalAmountCollected = 0;
        _amountToCollect = _amount! - walletBalance;
        notifyListeners();
        return;
      }
      _totalAmountCollected = walletBalance;

      _amountToCollect = 0;
      _selectdAccounts.forEach((element) {
        _totalAmountCollected =
            _totalAmountCollected + double.parse(element.amountSeected);
        _amountToCollect = amount! - _totalAmountCollected;
      });
      notifyListeners();
    } catch (e) {
      toast("Error: $e");
    }
  }


Widget button() {
    final TransacionProvider transferProvider =
        Provider.of<TransacionProvider>(context);
    final _size = MediaQuery.of(context).size;
    if (transferProvider.amountToCollect == null) {
      return buttonWraper(
          Text(
            "Insufficient Balance",
            style: getRegularStyle(color: ColorManager.whiteText, fontSize: 14),
          ),
          ColorManager.errorRed);
    }
    if (transferProvider.amountToCollect == 0) {
      return ConfirmationSlider(
        foregroundColor: ColorManager.background,
        sliderButtonContent: Shimmer.fromColors(
          baseColor: Color.fromARGB(255, 255, 255, 255),
          highlightColor: Color.fromARGB(255, 13, 13, 13),
          child: Icon(
            Icons.arrow_forward_ios_rounded,
            color: Colors.white,
            size: _size.width * 0.07,
          ),
        ),
        height: 60,
        width: 280,
        onConfirmation: () {
          validateData();
        },
        backgroundColor: ColorManager.grayLight,
        text: "Slide to Pay",
        textStyle: getBoldtStyle(
          color: ColorManager.whiteText,
          fontSize: 14,
        ),
        // stickToEnd: true,
      );
    }

    if (transferProvider.amountToCollect! < 0) {
      return buttonWraper(
        Text(
          "Exceeded amount required ",
          style: getRegularStyle(color: ColorManager.whiteText, fontSize: 14),
        ),
        ColorManager.grayLight,
      );
    }
    if (transferProvider.amountToCollect! > 0) {
      return buttonWraper(
          Text(
              " Please add \$${transferProvider.amountToCollect!.toStringAsFixed(2)} more.",
              style:
                  getRegularStyle(color: ColorManager.whiteText, fontSize: 14)),
          Color.fromARGB(255, 144, 169, 121));
    }
    return Container();
  }

when i remove or add account its not updating button as it is supposed to be,it working fine in debug mode

**Comment by bazl-E** [comment] 2022-07-28 11:01
Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => DataProvider()),
        ChangeNotifierProvider(create: (_) => AnimationProvider()),
        ChangeNotifierProvider(create: (_) => BusinessRegistrationProvider()),
        ChangeNotifierProvider(create: (_) => WalletProvider()),
        ChangeNotifierProvider(create: (_) => BankProvider()),
        ChangeNotifierProvider(create: (_) => ProfileProvider()),
        ChangeNotifierProvider(create: (_) => TransacionProvider()),
        ChangeNotifierProvider(create: (_) => TransacationhistoryProvider()),
      ],
      child: MaterialApp(
        title: 'Finwallet',
        debugShowCheckedModeBanner: false,
        theme: getApplicationTheme(context).copyWith(useMaterial3: true),
        onGenerateRoute: RouteGenerator.getRoute,
        initialRoute: Routes.splashRoute,
      ),
    );
  }

**Comment by bazl-E** [comment] 2022-07-28 11:02
@rrousselGit 
is there any mistake in this code

**Comment by rrousselGit** [comment] 2022-07-28 11:27
Thanks! Could you update your example such that it compiles? There's not much I can do with this, as I can't run it.

**Comment by bazl-E** [comment] 2022-07-29 08:50
@rrousselGit 
I found the issue
let me explain
im working in a mobile application which used to transfer money
there are two screens 
one for entering amount
2nd one for selecting bank account
the issue was rebuilding process was not happening even after calling notify listeners in the second screen.
but the problem was in 1st screen
what i was doing is in the 1st screen which mean int the amount entering screen's init state methode i was calling the following code 
....................................................................
  @override
  void initState() {
    super.initState();
    final transactionProvider =
        Provider.of<TransacionProvider>(context, listen: false);
    transactionProvider.setrecipient(widget.recipient);
  }
...................................................................
the transaction provide contains the following code 
...................................................................
class TransacionProvider with ChangeNotifier {
  Recipient? _recipient;
  Recipient? get recipient => _recipient;

  void setrecipient(Recipient? value) {
    _recipient = value;
  }
  List<SelectedAccount> _selectdAccounts = [];
  List<SelectedAccount> get selectdAccounts => _selectdAccounts;

  void insertSelectedAccount(SelectedAccount value, double walletBalance) {
    _selectdAccounts
        .removeWhere((element) => element.accountName == value.accountName);
    _selectdAccounts.add(value);
    settotalAmountCollected(walletBalance);
    notifyListeners();
  }

  void removeSelectedAccount(SelectedAccount value, double walletBalance) {
    print("removeSelectedAccount");
    _selectdAccounts
        .removeWhere((element) => element.accountName == value.accountName);
    print("removeSelectedAccount");
    settotalAmountCollected(walletBalance);
    notifyListeners();
  }

  double _totalAmountCollected = 0;
  double get totalAmountCollected => _totalAmountCollected;

  void settotalAmountCollected(double walletBalance) {
    print("settotalAmountCollected");
    if (_selectdAccounts.isEmpty) {
      _totalAmountCollected = 0;
      _amountToCollect = _amount! - walletBalance;

      notifyListeners();
      return;
    }
    _totalAmountCollected = walletBalance;

    _amountToCollect = 0;
    _selectdAccounts.forEach((element) {
      _totalAmountCollected =
          _totalAmountCollected + double.parse(element.amountSeected);
      _amountToCollect = amount! - _totalAmountCollected;
    });

    notifyListeners();
  }
}
...................................................................

i have confirm button in second screen(bank account selecting screen) which is supposed to change as user select or remove a bank account using the above function,the function was calling successfully in both release and debug mode but the rebuilding process was only happened in debug mode
so i changed the 1st screen initState methode as follows
...................................................................
 void initState() {
    super.initState();
 WidgetsBinding.instance.addPostFrameCallback((_) {
 final transactionProvider =
        Provider.of<TransacionProvider>(context, listen: false);
    transactionProvider.setrecipient(widget.recipient);
 });
}
...................................................................
and it starts working very fine........
i hope this will be helpful,

**Comment by Gene-Dana** [comment] 2022-08-08 19:08
> Please, for the love of gods, stop commenting "same issue".
> 
> Like I said, I need a way to reproduce the problem. If you don't give me a way to reproduce the problem, it's impossible for me to help you.
> 
> The only thing this kind of comment does is frustrate me.

Perhaps a better issues template could help

https://github.com/VeryGoodOpenSource/very_good_cli/tree/main/.github

**Comment by vivekvaghani** [comment] 2022-08-10 03:09
In my web project Provider State Management action working fine but the release mode of the web project Provider State Management action is not performing

Please resolve the issue as soon as possible

**Comment by johnmelodyme** [comment] 2022-08-30 09:41
> Please, for the love of gods, stop commenting "same issue".
> 
> Like I said, I need a way to reproduce the problem. If you don't give me a way to reproduce the problem, it's impossible for me to help you.
> 
> The only thing this kind of comment does is frustrate me.

Hey, fancy creating a Github action or installing Apps from the marketplace to monitor the issues with specific rules?

**Comment by rrousselGit** [comment] 2022-08-30 10:11
@johnmelodyme I've never heard about those. Any specific tool in mind?

**Comment by johnmelodyme** [comment] 2022-08-30 10:29
> @johnmelodyme I've never heard about those. Any specific tool in mind?

I am glad you asked.  :)

option 1, Using GitHub action like this https://github.com/flutter/flutter/tree/master/.github/workflows
option 2, Use [Stale](https://github.com/apps/stale) as used by [jitsi_meet](https://github.com/gunschu/jitsi_meet/issues/393#issuecomment-1230064925)

**Comment by rrousselGit** [comment] 2022-08-30 12:38
Thanks!

How do these tools help with unhelpful comments?

Afaik they seem to focus on closing issues that don't get reactions

Le mar. 30 août 2022 à 12:29, John Melody Me ***@***.***> a
écrit :

**Comment by ewaters** [comment] 2022-09-03 17:26
I came here with a similar issue, and found that my problem was solved similartly to bazl-E. In debug mode my app was working although it was throwing an error that I wasn't paying attention to: `setState() or markNeedsBuild() called during build.`.

I had some code that was indeed inadvertently calling `notifyListeners()` in my build function, and while it worked in debug mode, it didn't in release mode. I fixed this by wrapping the call in a `WidgetsBinding.instance.addPostFrameCallback()`.

**Comment by yoobright** [comment] 2022-09-26 06:21
> I came here with a similar issue, and found that my problem was solved similartly to bazl-E. In debug mode my app was working although it was throwing an error that I wasn't paying attention to: `setState() or markNeedsBuild() called during build.`.
> 
> I had some code that was indeed inadvertently calling `notifyListeners()` in my build function, and while it worked in debug mode, it didn't in release mode. I fixed this by wrapping the call in a `WidgetsBinding.instance.addPostFrameCallback()`.

I face same iussue. My solution is to remove unnecessary `notifyListeners()` in build function. And then everything looks fine.

**Comment by rrousselGit** [comment] 2022-10-11 07:03
Thanks for your comments everyone. I finally understand a bit more about the issue

If it's caused by people incorrectly calling `notifyListeners` within `build` and ignoring the error message, I'm not sure there's anything I can do.  
The best I could do is change the error message. But if it's ignored to begin with, I doubt it's going to do much

**Comment by rrousselGit** [comment] 2022-11-27 14:04
Closing since this isn't a Provider issue

**Closed by rrousselGit** 2022-11-27 14:04 UTC
Labels: bug, question
