### ISSUE TITLE
Provider docs don't mention the builder parameter

### ISSUE THREAD

**Issue by feinstein** [rrousselGit/provider#516] opened 2020-08-19 18:27 UTC
I was taking a look at the Provider source-code and I found this

https://github.com/rrousselGit/provider/blob/6f1913a8a16b42177537ec315f7b8b8ed7dfbfaa/lib/src/provider.dart#L128-L141

The `builder` parameter isn't being mentioned in the docs. Where is it useful? What cases should use it? This kind of information helps a lot.

Also, `MultiProvider` now also has a `builder` parameter, but its usages and examples aren't documented.

On top of that, the v3.x.0 to v4.0.0 migrations say `The parameters builder and initialBuilder of providers are removed.` but we clearly see it there, so this should be further clarified.

**Comment by rrousselGit** [comment] 2020-08-20 10:04
Duplicate of #512

**Closed by rrousselGit** 2020-08-20 10:04 UTC
Labels: documentation
