### ISSUE TITLE
Allow provider to be optional

### ISSUE THREAD

**Issue by jaumard** [rrousselGit/provider#437] opened 2020-05-05 07:47 UTC
So here is my use case, my package is using provider. And I want to retrieve my my object with `Provider.of<MyObject>(context)` but the user of the package have the choice to not provide me anything so I need something like `Provider.of<MyObject>(context, nullOk: true )` to retrieve null if there no MyObject provided to create it myself under the hood. 

Another use case would be to avoid having the default provider error message and put a nice error message contextualized of my package telling he have to initialize my package.

I've seen this `, nullOk: true ` in other inherited widget before. If there is another way of doing the please let me know

**Comment by rrousselGit** [comment] 2020-05-05 07:52
This is incompatible with non-nullable types

**Comment by jaumard** [comment] 2020-05-05 07:58
What are the alternative then ? Because those use cases are legit :)

**Comment by rrousselGit** [comment] 2020-05-05 08:09
You can catch the ProviderNotFoundException

Another possibility is to have `Provider.of(c, orElse: () => 42)`

**Comment by rrousselGit** [comment] 2020-05-06 16:24
Duplicate of #235

**Closed by rrousselGit** 2020-05-06 16:24 UTC
Labels: enhancement
