### ISSUE TITLE
proxy provider is not notifying my listeners

### ISSUE THREAD

**Issue by santosh81066** [rrousselGit/provider#780] opened 2022-09-25 05:02 UTC
I am trying to listen data but proxy provider is not listening but changenotifierproxyprovider is listening to data following is my code

```
void main() {
  Provider.debugCheckInvalidValueType = null;
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    //  final auth = Auth();
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(
          create: (_) => Auth(),
        ),
        ProxyProvider<Auth, ApiCalls>(
            create: (_) => ApiCalls(null),
            update: (_, auth, __) => ApiCalls(auth.token)),
```

**Comment by rrousselGit** [comment] 2022-09-25 11:39
Hello!

Could you update your example to be something that is self-contained and that can be executed? From what you shared, it isn't clear what the issue is, and as such there is no way for me to do anything.

**Comment by santosh81066** [comment] 2022-09-25 18:02
i am mailing you my running project sir here if you change proxyprovider to
changenotifierproxyprovider then you will see values in dropdown list after
login else if you use proxyprovider which is updated then you will not see
any values to login in app

username: admin
password:admin
 http_retry.zip
<https://drive.google.com/file/d/1h-X6CrMPFbPF6f4RpXrn5XwQcNfHWgLp/view?usp=drive_web>

**Comment by rrousselGit** [comment] 2022-09-25 22:23
Please don't mail an entire project

Instead find a way to reproduce the problem outside of your object, ideally on dartpad.

**Comment by santosh81066** [comment] 2022-09-26 07:13
```
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() {
  Provider.debugCheckInvalidValueType = null;
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<ThemeStyleBool>(
          create: (context) => ThemeStyleBool(themevalue: true),
        ),
        // ProxyProvider<ThemeStyleBool, MyTheme>(
        //   update: (context, value, previous) =>
        //       MyTheme(currenstate: value.getThemeValue),
        // ),
        ChangeNotifierProxyProvider<ThemeStyleBool, MyTheme>(
            create: (_) => MyTheme(),
            update: (context, value, previous) =>
                MyTheme(currenstate: value.getThemeValue)),
      ],
      child: Consumer<MyTheme>(
        builder: (context, value, child) {
          return MaterialApp(
              title: 'Flutter Demo',
              theme: value.getThemeData(),
              home: MyHomePage());
        },
      ),
      // : const AdminLoginScreen());
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String? selectedValue;
  @override
  void initState() {
    Provider.of<MyTheme>(context, listen: false).getlist();
    // TODO: implement initState
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    print('build');
    return Scaffold(
      appBar: AppBar(
        title: Text('explaining provider'),
      ),
      body: Column(
        children: [
          Consumer<MyTheme>(
            builder: (context, value, child) {
              return DropdownButton<String>(
                elevation: 16,
                isExpanded: true,
                hint: Text('please select type of vehicle'),
                items: value.list.map((v) {
                  return DropdownMenuItem<String>(value: v, child: Text(v));
                }).toList(),
                onChanged: (val) {
                  setState(() {
                    selectedValue = val!;
                  });
                },
                value: selectedValue,
              );
            },
          ),
          Consumer<ThemeStyleBool>(
            builder: (context, value, child) {
              return Expanded(
                child: Row(
                  children: [
                    Switch(
                        value: value.getThemeValue,
                        onChanged: (val) {
                          value.setThemeValue = val;
                        }),
                    Text(
                      'light/darkthem',
                      style: TextStyle(fontSize: 25),
                    )
                  ],
                ),
              );
            },
          )
        ],
      ),
    );
  }
}

class Constraints {
  static Color lightPrimary = Color(0xfff3f4f9);
  static Color darkPrimary = Color(0xff2B2B2B);
  static Color lightAccent = Color(0xff597ef7);
  static Color darkAccent = Color(0xff597ef7);
  static Color lightBg = Color(0xfff3f4f9);
  static Color darkBg = Color(0xff2B2B2B);
  static ThemeData lightTheme = ThemeData(
    backgroundColor: lightBg,
    primaryColor: lightPrimary,
    scaffoldBackgroundColor: lightBg,
    appBarTheme: AppBarTheme(
        elevation: 3,
        toolbarTextStyle: const TextTheme(
                headline6: TextStyle(
                    color: Colors.black,
                    fontSize: 20,
                    fontWeight: FontWeight.bold))
            .bodyText2,
        titleTextStyle: const TextTheme(
                headline6: TextStyle(
                    color: Colors.black,
                    fontSize: 20,
                    fontWeight: FontWeight.bold))
            .headline6),
  );
  static ThemeData darkTheme = ThemeData(
    brightness: Brightness.dark,
    backgroundColor: darkBg,
    primaryColor: darkPrimary,
    scaffoldBackgroundColor: darkBg,
    appBarTheme: AppBarTheme(
        elevation: 2,
        toolbarTextStyle: TextTheme(
                headline6: TextStyle(
                    color: lightBg, fontSize: 20, fontWeight: FontWeight.bold))
            .bodyText2,
        titleTextStyle: const TextTheme(
                headline6: TextStyle(
                    color: Colors.black,
                    fontSize: 20,
                    fontWeight: FontWeight.w800))
            .headline6),
  );
}

class ThemeStyleBool extends ChangeNotifier {
  bool? themevalue;
  ThemeStyleBool({this.themevalue});
  bool get getThemeValue {
    return themevalue!;
  }

  set setThemeValue(bool value) {
    themevalue = value;
    notifyListeners();
  }
}

class MyTheme extends ChangeNotifier {
  final bool? currenstate;
  MyTheme({this.currenstate});
  List list = [];

  ThemeData getThemeData() {
    if (currenstate!) {
      return Constraints.darkTheme;
    }
    return Constraints.lightTheme;
  }

  void getlist() {
    list = ['one', 'two', 'three'];
    notifyListeners();
  }
}

```

**Comment by santosh81066** [comment] 2022-09-26 07:17
you can post this code in flutter directly and you can run here I n above code I had used   ChangeNotifierProxyProvider you can comment it and uncomment proxy provider to see difference you will observe that values are not loading in dropdown list while I use proxy provider

**Comment by rrousselGit** [comment] 2022-09-26 17:00
Thanks for the detailed example!


That behavior is expected. Since MyTheme is a ChangeNotifier, you should use ChangeNotifierProxyProvider

ProxyProvider does not listen to the object returned, nor does it disposes the ChangeNotifier when a dependency changes

**Comment by santosh81066** [comment] 2022-09-26 19:20
ok thank you for clarifying i am having doubt because there is no
documentation written for changenotifierproxyprovider can you please
provide docs for changenotifierproxyprovider it would be useful to other
users as well thank you

**Comment by rrousselGit** [comment] 2022-10-11 07:04
Closing since this was clarified and expected

**Closed by rrousselGit** 2022-10-11 07:04 UTC
Labels: bug, question
