### ISSUE TITLE
FutureProvider triggers ConcurrentModificationError

### ISSUE THREAD

**Issue by digitalkaoz** [rrousselGit/provider#331] opened 2020-01-28 19:42 UTC
Hello there,

first, thanks for this great module and your hard work!

im trying to put a `SharedPreferences` (https://pub.dev/packages/shared_preferences) instance into a provider, and reuse this Provider in several other Providers.

```dart
final List<InheritedProvider> providers = [
  FutureProvider<SharedPreferences>(
    create: (_) => SharedPreferences.getInstance(),
  ),
  ProxyProvider<SharedPreferences, Storage>(
    update: (_, prefs, __) => LocalStorage(prefs),
  ),
];

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: providers,
      child: MaterialApp(/*...*/),
    );
  }
}
```

this triggers this warning:

```
I/flutter ( 7314): The following ConcurrentModificationError was thrown building
I/flutter ( 7314): _DefaultInheritedProviderScope<SharedPreferences>(dirty, controller: Instance of
I/flutter ( 7314): 'Future<SharedPreferences>', value: Instance of 'SharedPreferences'):
I/flutter ( 7314): Concurrent modification during iteration: Instance of '_HashMap<Element, Object>'.
I/flutter ( 7314): 
I/flutter ( 7314): The relevant error-causing widget was:
I/flutter ( 7314):   _DefaultInheritedProviderScope<SharedPreferences>
I/flutter ( 7314):   file:///opt/flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.0.2/lib/src/inherited_provider.dart:113:12
I/flutter ( 7314): 
I/flutter ( 7314): When the exception was thrown, this was the stack:
I/flutter ( 7314): #0      _HashMapIterator.moveNext (dart:collection-patch/collection_patch.dart:481:7)
I/flutter ( 7314): #1      InheritedElement.notifyClients (package:flutter/src/widgets/framework.dart:4840:43)
I/flutter ( 7314): #2      _InheritedProviderScopeMixin.build (package:provider/src/inherited_provider.dart:281:7)
I/flutter ( 7314): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4226:15)
I/flutter ( 7314): #4      _InheritedProviderScopeMixin.performRebuild (package:provider/src/inherited_provider.dart:220:11)
```

i dont see what might be wrong here.

**Comment by lookfirst** [comment] 2020-01-28 20:45
With latest api...

```
List<SingleChildWidget> dependentServices = [
  FutureProvider.value(value: SharedPreferences.getInstance()),
  ProxyProvider<SharedPreferences, StorageService>(
    update: (context, prefs, storage) => StorageService(prefs: prefs),
  ),
];
```

**Comment by digitalkaoz** [comment] 2020-01-28 20:48
@lookfirst got the same error

**Comment by lookfirst** [comment] 2020-01-28 22:24
ok, that has me a bit worried... i'm trying to upgrade all my versions to latest and see what happens...

**Comment by lookfirst** [comment] 2020-01-29 01:31
seems to work ok on my end... maybe something in the creation of `LocalStorage` or other code in your app?

**Comment by rrousselGit** [comment] 2020-02-10 11:04
Could you share a runnable code example?
I do not know what that `Storage` is and therefore cannot help.

**Comment by digitalkaoz** [comment] 2020-02-10 12:39
i solved it differently, but that doesnt answers the current question:

```dart
List<InheritedProvider> createProviders(SharedPreferences prefs) {
  return [
    Provider<Storage>(
      create: (_) => LocalStorage(prefs),
    ),
  ];
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: SharedPreferences.getInstance(),
      builder: (BuildContext context, AsyncSnapshot<SharedPreferences> snap) {
        if (ConnectionState.done != snap.connectionState) {
          return LoadingPage();
        }

        return MultiProvider(
          providers: createProviders(snap.data),
          child: PlatformApp(),
        );
      },
    );
  }
}
```

so basically not use the `FutureProvider` but instead a `FutureBuilder` and use the result `SharedPreferences` to create the container...Not what i had in mind, but a working solution.

it doesnt matter what happens inside the `Storage` class as a simple instantiation already fails (afaik)

**Comment by lookfirst** [comment] 2020-02-10 15:18
Nice solution, but I'm curious why it works for me and not for you! =)

**Comment by rrousselGit** [comment] 2020-06-04 23:49
Considering the issue is old and without answer, I'll close this for now.

If you still have problem, feel free to say so!

**Closed by rrousselGit** 2020-06-04 23:49 UTC
Labels: question
