### ISSUE TITLE
Provider fails when I pop navigator twice

### ISSUE THREAD

**Issue by nmhernandez10** [rrousselGit/provider#362] opened 2020-02-25 16:05 UTC
I use Providers for state management. I use an Alert Dialog to confirm a navigator.pop() on a specific screen, but when they confirm it, navigator pops twice (pop dialog -> pop screen) and  provider does not notify changes to children anymore. This only happens on release mode, when app runs on debug mode it works perfectly.

**Comment by rrousselGit** [comment] 2020-02-25 16:13
Hello

I need a way to consistently reproduce the issue, otherwise I cannot help you.

**Comment by nmhernandez10** [comment] 2020-02-25 19:20
I tried to reproduce it in a new application and it worked perfectly with no errors. I can't send you the real application because it has sensitive information. The original app contians complex packages (firebase auth, firebase storage, firebase firestore, etc.), and I use many provider (7) with Multiprovider widget. Is there any limit to the number of simultaneous providers?  Is there any other channel from which you could help me? :c

**Comment by rrousselGit** [comment] 2020-02-25 19:32
Your best bet will be to remove a bunch of code in your real app until you manage to pin-point the problem.

This may be unrelated to provider. It may be one of your `ChangeNotifier` not calling `notifyListener` in release mode for example.

**Comment by nmhernandez10** [comment] 2020-02-25 19:56
Why one of my ChangeNotifier would stop calling their listeners in release mode? I made an experimental change and it solved my problem:

- The raised button onPressed callback was: 

() {
 Navigator.of(context).pop();
 Navigator.of(context).pop();
}

- The 'solution' is:

() async {
 Navigator.of(context).pop();
 await Future.delayed(
                  Duration(milliseconds: 500),
                );
 Navigator.of(context).pop();
}

Appearently, waiting a half second fixes my issue. It does not work in release mode because the execution time of code is faster than debug mode? In debug mode it's not necessary any delay, it works nice. It is weird, why a delay would solve the problem?

**Comment by rrousselGit** [comment] 2020-02-25 20:30
Do you mind showing the related parts of your ChangeNotifier?

**Comment by rrousselGit** [comment] 2020-06-04 23:46
Considering the issue is old and without answer, I'll close this for now.

If you still have problem, feel free to say so!

**Closed by rrousselGit** 2020-06-04 23:46 UTC
Labels: question
