### ISSUE TITLE
Cannot provide bloc from inside of other widgets ? 

### ISSUE THREAD

**Issue by shashikantx** [rrousselGit/provider#85] opened 2019-05-24 11:05 UTC
As I was thinking of using Provider + BLoC. Usually with Inherited widget what is possible is to provide a bloc specific to the route / sub child widgets. 

When I tried the same with Provider it fails to recognize the Bloc? 

But same works in case If I initiate bloc from outside of MaterialApp.

```

void main() {
  runApp(
    Provider<DevicesBloc>(
      builder: (ctx) => DevicesBloc(),
      child: MaterialApp(
          title: 'WaterLeveller',
          home: DevicesListScreen(),
        ),
      ),    
  );
}

class DevicesListScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Color(0xFF448C33),
        title: const Text("Water Leveler"),
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.add),
            onPressed: () {
              Navigator.push(context,
                  MaterialPageRoute(builder: (context) => AddDeviceScreen()));
            },
          )
        ],
      ),
      body: Container(
          child: ListView(
            children: <Widget>[
              GestureDetector(              
                child: Padding(
                  padding: EdgeInsets.all(30),
                  child: Text("List 1"),
                ),
              )
            ],
          ),
        ),    
    );
  }
}
```

Those are the parent widgets, and the below one is child widget, In which I have a button "Add" on press, I would like to call a function inside the DevicesBloc, which works in this case.

```
class AddDeviceScreen extends StatelessWidget{
  @override
  Widget build(BuildContext context) {    
    return Scaffold(
      appBar: AppBar(
        title: Text("Add Device"),
      ),
      body: Container(
        margin: EdgeInsets.all(20.0),
        child: Column(
          children: <Widget>[
            TextFormField(
              decoration: InputDecoration(
                hintText: "Device Name"
              ),
              style: TextStyle(
                
              ),
            ),
            Padding(
              padding: const EdgeInsets.fromLTRB(0,14.0,0,0),
              child: RaisedButton(
                onPressed: (){
                  Provider.of<DevicesBloc>(context).addDevice();
                },
                child: Text("Add"),
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

But same won't work in case I move the bloc provide inside DeviceListScreen like this.

```

void main() {
  runApp(
   MaterialApp(
          title: 'WaterLeveller',
          home: DevicesListScreen(),
        ),       
  );
}


class DevicesListScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Provider<DevicesBloc>(
      builder: (ctx) => DevicesBloc(),
      child: Scaffold(
        appBar: AppBar(
          backgroundColor: Color(0xFF448C33),
          title: const Text("Water Leveler"),
          actions: <Widget>[
            IconButton(
              icon: Icon(Icons.add),
              onPressed: () {
                Navigator.push(context,
                    MaterialPageRoute(builder: (context) => AddDeviceScreen()));
              },
            )
          ],
        ),
        body: Container(
          child: ListView(
            children: <Widget>[
              GestureDetector(
                child: Padding(
                  padding: EdgeInsets.all(30),
                  child: Text("List 1"),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}
```

This throws this exception. 

```
I/flutter (18418): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (18418): The following ProviderNotFoundError was thrown while handling a gesture:
I/flutter (18418): Error: Could not find the correct Provider<DevicesBloc> above this AddDeviceScreen Widget
I/flutter (18418):
I/flutter (18418): To fix, please:
I/flutter (18418):
I/flutter (18418):   * Ensure the Provider<DevicesBloc> is an ancestor to this AddDeviceScreen Widget
I/flutter (18418):   * Provide types to Provider<DevicesBloc>
I/flutter (18418):   * Provide types to Consumer<DevicesBloc>
I/flutter (18418):   * Provide types to Provider.of<DevicesBloc>()
I/flutter (18418):   * Always use package imports. Ex: `import 'package:my_app/my_code.dart';
I/flutter (18418):   * Ensure the correct `context` is being used.
I/flutter (18418):
I/flutter (18418): If none of these solutions work, please file a bug at:
I/flutter (18418): https://github.com/rrousselGit/provider/issues
```

Which in my opinion should be possible ? Or is it something should not be done?

**Comment by rrousselGit** [comment] 2019-05-24 11:11
To make a data available only to a specific set of routes, you'll need to use named routes.

Here's a typical example, where `/` can read `MyBloc` but `/a` can't:

```dart
class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  MyBloc myBloc = MyBloc();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {
        '/': Provider.value(value: myBloc, child: Home()),
        // can't access MyBloc:
        '/a': A(),
      },
    );
  }
}
```

**Comment by shashikantx** [comment] 2019-05-24 11:17
Could I not do it dynamically ? Without using named routes? 

Anyways, it would be nice if it was documented somewhere how to do it. Both ways if possible.

**Comment by roughike** [comment] 2019-05-24 11:30
You could also do a dynamic route like this:

```dart
class MyDetailsScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Provider<MyDetailsBloc>(
      builder: (_) => MyDetailsBloc(),
      dispose: (_, bloc) => bloc.dispose(),
      child: _Content(),
    );
  }
}

class _Content extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final bloc = Provider.of<MyDetailsBloc>(context);

    return Container(..);
  }
}
```

Then you'd call `Navigator.push(context, MaterialPageRoute(builder: (_) => MyDetailsScreen()));` like you'd normally do.

**Comment by rrousselGit** [comment] 2019-05-24 11:38
@roughike has a point, but that code is not what you want if you need multiple routes to _share_ state.

To do that, you need to push your dynamic route from a route that can access the provided value.

Then your `push` will look like this:


```dart
final myBloc = Provider.of<MyBloc>(context);
Navigator.push(context, MaterialPageRoute(builder: (_) => Provider.value(value: myBloc, MyDynamicScreen()));
```

**Comment by shashikantx** [comment] 2019-05-24 12:15
@rrousselGit  Yes that fixes the issue, 

Thanks @roughike @rrousselGit

**Comment by landon-sf** [comment] 2019-05-25 19:09
I don't mean to pile on this issue but since it was open... :-)

I am in the exact situation, thanks for clarifying how we need to pass  state on a push.  However, seems like the `MyDynamicScreen` is not getting notified of the changes to properties defined on `MyBloc` even though I see the call to set state happening when notifyListeners gets called.  Is this by design in this scenario?

BTW thanks for all of the work on this package, its amazing!

**Comment by rrousselGit** [comment] 2019-05-25 20:39
@landon-sf yes, that's to be expected for anything that is not a stream/ChangeNotifier/ValueNotifier

In general, you should move your state above `MaterialApp` in that situation

**Comment by landon-sf** [comment] 2019-05-26 00:07
@rrousselGit `MyBloc` in this case extends `ChangeNotifier` and it seems that every time I change a property in `MyBloc` it would notify `MyDynamicScreen` to rebuild unless I am missing something.

**Comment by rrousselGit** [comment] 2019-05-26 03:32
Then on the precious example, use `ChangeNotifierProvider`

**Comment by landon-sf** [comment] 2019-05-26 06:32
Thanks for the insight, I've figured things out.

**Comment by saviourdog** [comment] 2019-05-26 13:44
> I don't mean to pile on this issue but since it was open... :-)
> 
> I am in the exact situation, thanks for clarifying how we need to pass state on a push. However, seems like the `MyDynamicScreen` is not getting notified of the changes to properties defined on `MyBloc` even though I see the call to set state happening when notifyListeners gets called (essential not rebuilding). Is this by design in this scenario?
> 
> BTW thanks for all of the work on this package, its amazing!

same question

**Comment by landon-sf** [comment] 2019-05-26 17:16
@saviourdog essentially flutter doesn't build the tree based on the navigation.  In my example when pushing the `OtherWidget` it is no longer under the `Home` widget that has the `ChangeNotifierProvider`

**Comment by landon-sf** [comment] 2019-05-26 17:17
@rrousselGit I think this issue can be closed.

**Comment by rrousselGit** [comment] 2019-05-26 17:26
I'm leaving it open to track what needs an example.

**Comment by namaye** [comment] 2019-05-30 07:57
Question 1 -
```
Provider<MyBloc>(
   builder: (_) => MyBloc(),
   dispose: (_, bloc) => bloc.dispose(),
   child: _MyContent(),
);
```

My understanding is, the above code will automatically call the dispose method in the bloc when needed. Will the following implementation will also do the same or do I need to dispose it manually.

```
Provider.value(
   value: Provider.of<MyBloc>(context),
   child: _MyContent(),
);
```

Question 2 -
Is StreamProvider same as the StreamBuilder, or is there any merit in using one over the other. Thank you.

**Comment by junjizhi** [comment] 2019-07-01 22:36
> @landon-sf yes, that's to be expected for anything that is not a stream/ChangeNotifier/ValueNotifier

Suggestion: Add this line to **Reading a value** section in README, to clarify that widgets won't get rebuilt even though the value changes. We can consider using stream/ChangeNotifier/ValueNotifier. 

Hopefully, it helps future newcomers to this package like me to be less confused about the usage examples.

**Comment by rrousselGit** [comment] 2019-07-01 23:05
To be honest, I have other plans.

Instead tricks around `Navigator` like this one:

```dart
final myBloc = Provider.of<MyBloc>(context);
Navigator.push(context, MaterialPageRoute(builder: (_) =>
    Provider.value(
      value: myBloc,
      child: MyDynamicScreen(),
    ),
));
```

then we'd have a global provider lazily-loaded

**Comment by Iampopal** [comment] 2019-09-16 10:35
> ```dart
> myBloc
> ```

This way i can send one block value, how to send multiple blocks to new screen with Navigator?

**Comment by danallen88** [comment] 2019-09-23 16:12
Is it fair to say that a ChangeNotifierProvider and Consumer cannot be used across the boundary of a dynamic route?  I'm finding that even if I provide a model value as an ancestor to a widget that tries to push a dynamic route, I cannot even make the route target a consumer of the model, which is odd since it seems to happen before the target is constructed.  For example:

```dart
child: ChangeNotifierProvider<RunDetailsModel>(
          builder: (context) => RunDetailsModel(),
          child: RunHeader(),
        ),
```
and in the `RunHeader` widget I have an element with the following:

```dart
onPressed: () {
    Navigator.push(
         context,
         MaterialPageRoute(
               builder: (context) => Consumer<RunDetailsModel>(
                    builder: (context, runDetailsModel, child) => ResultDetailsPage(runDetailsModel.runDetails)
                ),
          ),
    );
}
```

this results in the following error:
```
The following ProviderNotFoundError was thrown building Consumer<RunDetailsModel>(dirty):
Error: Could not find the correct Provider<RunDetailsModel> above this Consumer<RunDetailsModel> Widget

To fix, please:

  * Ensure the Provider<RunDetailsModel> is an ancestor to this Consumer<RunDetailsModel> Widget
  * Provide types to Provider<RunDetailsModel>
  * Provide types to Consumer<RunDetailsModel>
  * Provide types to Provider.of<RunDetailsModel>()
  * Always use package imports. Ex: `import 'package:my_app/my_code.dart';
  * Ensure the correct `context` is being used.

If none of these solutions work, please file a bug at:
https://github.com/rrousselGit/provider/issues
When the exception was thrown, this was the stack: 
#0      Provider.of (package:provider/src/provider.dart:260:7)
#1      Consumer.build (package:provider/src/consumer.dart:182:16)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3974:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
```

**Comment by rrousselGit** [comment] 2019-09-23 16:32
> I'm finding that even if I provide a model value as an ancestor to a widget that tries to push a dynamic route

Here's the trick: pushed routes are not descendants of the previous routes. They are in a different branch

And since providers are scoped, then the value is accessible only from the original route

**Comment by shadysamara** [comment] 2020-01-18 00:37
i have a similar issue here
i am trying to call a method (changeLoadingState) that i defined inside the provider class from the main page as the follows:

`class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (context) => LoadingModel(),
      child: MaterialApp(
        home:Scaffold(
          body: Center(
            child: 
                RaisedButton(
              child: Text("hide the progress"),
              onPressed: () {

              **Provider.of<LoadingModel>(context,listen: false).changeLoadingState();**
                
                },
            ).............`


bur when i press on the button this what is appeared on the console :

Error: Could not find the correct Provider<LoadingModel> above this MyApp Widget

To fix, please:

  * Ensure the Provider<LoadingModel> is an ancestor to this MyApp Widget
  * Provide types to Provider<LoadingModel>
  * Provide types to Consumer<LoadingModel>
  * Provide types to Provider.of<LoadingModel>()
  * Always use package imports. Ex: `import 'package:my_app/my_code.dart';
  * Ensure the correct `context` is being used.

If none of these solutions work, please file a bug at:
https://github.com/rrousselGit/provider/issues

**Comment by rrousselGit** [comment] 2020-04-11 09:56
Closing this, as 4.0.0 introduced lazy-loaded providers, which is an indirect fix to this problem.

**Closed by rrousselGit** 2020-04-11 09:56 UTC
Labels: documentation
