### ISSUE TITLE
StreamProvider doesn't work when depending on ProxyProvider after migration to v4

### ISSUE THREAD

**Issue by nomyzs** [rrousselGit/provider#340] opened 2020-02-07 17:36 UTC
Below you'll find a simple example app that reproduces the problem.
Maybe worth mentioning that StreamProvider that depends on regular Provider works fine.

For those interested, workaround mentioned here https://github.com/rrousselGit/provider/issues/120#issuecomment-501178509 is working fine 

Hope that helps, and again, thanks for this library!

```dart
import 'dart:async';
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Provider(
      create: (context) => ApiService(),
      child: Builder(
        builder: (context) {
          return ProxyProvider<ApiService, AuthService>(
            create: (context) => AuthService(),
            update: (context, apiService, authService) => AuthService(),
            child: Builder(builder: (context) {
              return StreamProvider(
                create: (context) =>
                    Provider.of<AuthService>(context, listen: false).userId,
                child: MaterialApp(
                  title: 'Flutter Demo',
                  theme: ThemeData(
                    primarySwatch: Colors.blue,
                  ),
                  home: MyHomePage(title: 'Flutter Demo Home Page'),
                ),
              );
            }),
          );
        },
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _userId;

  void _incrementCounter() {
    Provider.of<AuthService>(context, listen: false).changeUserId();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              _userId ?? "no user id",
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }

  @override
  void didChangeDependencies() {
    String userId = Provider.of<String>(context);
    if (userId != _userId) {
      setState(() {
        _userId = userId;
      });
    }

    super.didChangeDependencies();
  }
}

class AuthService {
  Stream<String> get userId => _accountController.stream;

  StreamController<String> _accountController = StreamController<String>();

  void changeUserId() {
    _accountController.add(_randomString(6));
  }
}

String _randomString(int length) {
  var rand = new Random();
  var codeUnits = new List.generate(length, (index) {
    return rand.nextInt(33) + 89;
  });

  return new String.fromCharCodes(codeUnits);
}

class ApiService {}

```

**Comment by rrousselGit** [comment] 2020-02-07 17:45
I see code, but whats the problem?

**Comment by nomyzs** [comment] 2020-02-10 10:22
`didChangeDependencies()` is not called anymore with updated value

**Comment by rrousselGit** [comment] 2020-02-10 10:59
I can't reproduce it. This works for me.

Could you write a test case that fails?

**Comment by juanpare-peya** [comment] 2020-02-27 19:10
Hi, I am getting the same problem with provider 4.0.4.

@nomyzs you found a fix for this?

**Comment by nomyzs** [comment] 2020-02-28 10:09
Atm using 4.0.3. But workaround I mentioned seems to be working fine. 
This one https://github.com/rrousselGit/provider/issues/120#issuecomment-501178509

**Comment by rrousselGit** [comment] 2020-02-28 10:57
No worries.
I would just reiterate on the fact that I cannot reproduce this. So I have no idea on how to fix it, or if there's even something to fix 😕

**Comment by rrousselGit** [comment] 2020-06-04 23:48
Considering the issue is old and I have no way to reproduce the problem.

If you still have problem, feel free to say so!

**Closed by rrousselGit** 2020-06-04 23:48 UTC
Labels: question
