### ISSUE TITLE
Why does Provider.of( listen: false) will still trigger the widget rebuild?

### ISSUE THREAD

**Issue by jims57** [rrousselGit/provider#477] opened 2020-06-18 16:54 UTC
[main.dart.zip](https://github.com/rrousselGit/provider/files/4799989/main.dart.zip)
![image](https://user-images.githubusercontent.com/1920873/85049556-6471a880-b1c7-11ea-89c0-3251c2aa988e.png)

**Comment by rrousselGit** [comment] 2020-06-18 17:05
I don't understand. Are you expecting `Consumer` not to be called again?

**Comment by jims57** [comment] 2020-06-18 17:15
@rrousselGit According the [doc](https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple#providerof), when **listen** is set **false**, it won’t cause this widget to rebuild when notifyListeners is called.

Since the doc I mentioned above is related to the tutorial about state management involving **Consumer**, **ChangeNotifier** and **ChangeNotifierProvider**, I expect that the **builder** callback method in **Consumer** won't be triggered.

Am I right? Thanks.

> I don't understand. Are you expecting `Consumer` not to be called again?

**Comment by rrousselGit** [comment] 2020-06-18 17:52
Consumer doesn't have a "listen" flag. It is unrelated to Provider.of

**Comment by Zengyonghao** [comment] 2020-06-19 10:36
> @rrousselGit
> Yes, I am expecting **Consumer** not to be called, for I don't want the Widget to rebuild again, I just want to delete data in the background.
> 
> According the [doc](https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple#providerof), when **listen** is set **false**, it won’t cause this widget to rebuild when notifyListeners is called.
> 
> Since the doc I mentioned above is related to the tutorial about state management involving **Consumer**, **ChangeNotifier** and **ChangeNotifierProvider**, I expect that the **builder** callback method in **Consumer** won't be triggered.
> 
> Am I right? Thanks.
> 
> > I don't understand. Are you expecting `Consumer` not to be called again?

You can think of **Consumer** as **Provider.of (contxt,true)**,
notify will cause it to build()

**Comment by jims57** [comment] 2020-06-24 02:35
> You can think of **Consumer** as **Provider.of (contxt,true)**,
> notify will cause it to build()

@Zengyonghao Actually, I can't find the difference between **Provider.of(context,false)** and **Provider.of(Cotext.true)**,  since I see both will trigger the rebuild of widget(Not **Consumer**, I mean normal widgets, such as **Text**), I am expecting **Provider** is used to rebuild on-demand for widget apart from providing **app** level state.

**Comment by diegoveloper** [comment] 2020-06-29 06:13
The documentation is really clear about how `Consumer` and `Provider.of` work with and without `listen`  flag.

You can use these samples using both ways.

```dart

class SampleProvider extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => Counter()),
      ],
      child: MyHomePage(),
    );
  }
}

```

Using `Provider.of` and `listen:true` (by default).

~ Every time you call `increment` method its rebuild all the widget.

```dart

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final counter = Provider.of<Counter>(context);
    print('build $this');
    return Scaffold(
      appBar: AppBar(
        title: const Text('Example'),
      ),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text(
              counter.count.toString(),
              style: Theme.of(context).textTheme.headline5,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => counter.increment(),
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

Using `Consumer` and `listen:false`.

~ Every time you call `increment` method its rebuild only the widget inside the `Consumer`.

```dart
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('build $this');
    final counter = Provider.of<Counter>(context, listen: false);
    return Scaffold(
      appBar: AppBar(
        title: const Text('Example'),
      ),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Consumer<Counter>(
              builder: (_, value, __) {
                print('build consumer $this');
                return Text(
                  value.count.toString(),
                );
              },
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => counter.increment(),
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

Check the print statements I added and see how it shows.

**Comment by rrousselGit** [comment] 2020-07-06 09:14
Closing as this is working as expected – Consumer always listens to changes in the object

**Closed by rrousselGit** 2020-07-06 09:14 UTC
Labels: question

**Comment by AndrewByk** [comment] 2020-12-08 21:41
Then what the point of listen=false?

**Comment by diegoveloper** [comment] 2020-12-08 21:47
> Then what the point of listen=false?

The point is not to listen to the values values, only to have access to the providers.

**Comment by rrousselGit** [comment] 2020-12-09 02:15
> Then what the point of listen=false?

It prevents rebuilds caused by the specific provider you are reading. But the widget will still rebuild from other sources
