### ISSUE TITLE
Consumer and ChangeNotifierProxyProvider inconsistencies.

### ISSUE THREAD

**Issue by TannerYoung** [rrousselGit/provider#175] opened 2019-07-26 11:56 UTC
When consuming from a proxied change notifier provider, it appears that there is inconsistency over which consumers get updated.

A complete example is below. In the example an int is updated by a button press, and is translated into a string which also is a change notifier. In a more complex example the string would have different buttons acting on it modifying it as well. 

I would expect all 5 fields in the example to be updated, but only fields 3 and 4 are when the button is pressed.

```
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() {
  runApp(DemoApp());
}

class DemoApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      body: SafeArea(
        child: ChangeNotifierProvider(
          builder: (_) => ValueNotifier(1),
          child: ChangeNotifierProxyProvider<ValueNotifier<int>, ValueNotifier<String>>(
            builder: (ctx, valueIntOuter, prev) {
              print("The string notifier gets built every time.");
              return ValueNotifier(valueIntOuter.value.toString());
            },
            child: Consumer<ValueNotifier<String>>(builder: (ctx, ValueNotifier<String> valueStringOuter, _) {
              print("This string notifier consumer build is only ever called once.");
              return Column(
                children: <Widget>[
                  // This one is NOT updated on the button press.
                  Text("Field 1: ${valueStringOuter.value}"),

                  // This one is NOT updated on the button press.
                  Consumer<ValueNotifier<String>>(builder: (ctx, valueStringInner, _) =>
                    Text("Field 2: ${valueStringInner.value}"),
                  ),

                  Consumer<ValueNotifier<int>>(
                    builder: (ctx, valueIntOuter, child) =>
                        Column(
                          children: <Widget>[
                            // This is updated on the button press.
                            Text("Field 3: ${valueIntOuter.value.toString()}"),

                            // This is updated on the button press??
                            Consumer<ValueNotifier<String>>(builder: (ctx, valueStringInner, _) =>
                                  Text("Field 4: ${valueStringInner.value}"),
                            ),

                            // This one is also NOT updated on the button press.
                            Text("Field 5: ${valueStringOuter.value}"),

                            FlatButton(
                              child: Text("Presse me."),
                              onPressed: () {
                                print("The button is pressed!");
                                return valueIntOuter.value += 1;
                              },
                            ),
                          ],
                        ),
                  ),
                ],
              );
            }),
          ),
        ),
      ),
    ));
  }
}
```

**Comment by rrousselGit** [comment] 2019-07-26 13:06
This looks like a duplicate of https://github.com/rrousselGit/provider/issues/139#issuecomment-508569809

**Closed** 2019-07-26 13:26 UTC
