### ISSUE TITLE
Allow `Provider.of` to return null instead of throwing ProviderNotFoundError

### ISSUE THREAD

**Issue by ds84182** [rrousselGit/provider#235] opened 2019-10-09 22:40 UTC
This would be a very small patch.. e.g:

```dart
static T of<T>(BuildContext context, {bool listen = true, bool allowNull = false}) {
  // ...

  if (provider == null && !allowNull) {
    throw /* ... */;
  }

  return provider?._value;
}
```

Yes, a provider being absent from the tree should be an error in most cases, but there are some times where you want to optionally provide something down to the rest of the tree. I've run into this multiple times when working with provider, and in some cases it's more useful to manually write an inherited widget.

**Comment by mono0926** [comment] 2019-10-10 02:57
I think `bool nullOk = false` is better than `bool allowNull = false` for consintency.

Flutter framework uses that term like this:
https://github.com/flutter/flutter/blob/2d2a1ffec95cc70a3218872a2cd3f8de4933c42f/packages/flutter/lib/src/material/scaffold.dart#L1256

**Comment by rrousselGit** [comment] 2019-10-10 09:45
Alternatively, we can remove the exception and always make the result of `.of` nullable.

That'd be a breaking change (and pretty boring to use). But it's safer.

**Comment by ds84182** [comment] 2019-10-10 17:42
I like `maybeOf` a bit more. It'll get really weird with NNBD though, since you can have a provider that provides a nullable value.

What about doing `return provider?._value as T;`? Then the optionality is encoded in the type system, since this will throw an error at runtime.

I think you might also be able to test whether a type is nullable by doing `if (null is T)`, so another alternative is to do:

```dart
static T of<T>(BuildContext context, {bool listen = true}) {
  // ...

  if (provider == null) {
    if (null is T) {
      return null;
    } else {
      throw /* ... */;
    }
  }

  return provider?._value as T; // T? to T, if T is already nullable then T?? == T? which never fails
}
```

**Comment by rrousselGit** [comment] 2019-10-10 18:09
That'd cause a problem with non-nullable providers, while trying to handle the "there's no provider" scenario.

Consider the following NNBD snippet:

```dart
Provider<Model>(
  builder: (_) => Model()),
  child: ...
)
```

Then if we want to obtain `Model` while handling the "no provider" case, then we'd have to do:

```dart
Provider.of<Model?>(context)
```

The issue is,  that won't work because `Model` is obtained through a `runtimeType` comparison. And `Model != Model?`, so no provider will ever be found.

It's probably an edge case though.

**Comment by ds84182** [comment] 2019-10-11 02:38
Ah yeah, would help if we could do `!` on types too.

**Comment by rrousselGit** [comment] 2019-10-11 12:49
> Ah yeah, would help if we could do `!` on types too.

It's possible. But I don't see how that would help

**Comment by rrousselGit** [comment] 2019-10-12 11:08
Also, note that it's already feasible to handle such a scenario with a `try catch`.

**Comment by ds84182** [comment] 2019-10-13 17:52
@rrousselGit Not exactly, people who use strict lints against catching `Error`s will have to insert an `// ignore` comment. It's considered bad style to catch anything extending from `Error`, since it indicates "programmer error" and not "exceptional situation".

**Comment by rrousselGit** [comment] 2019-10-13 17:55
Right. But we can rename ProviderNotFoundError to ProviderNotFoundException.

**Comment by adriancmurray** [comment] 2019-10-14 22:05
> Also, note that it's already feasible to handle such a scenario with a `try catch`.

With this mentioned the solution wasn't too terrible for now. Just use the normal `static of(context)` method for retrieval and it works just fine. This could also be a method to inject a quick solution for [#244](https://github.com/rrousselGit/provider/issues/244)

```
static Model of(context, {bool allowNull = false}) {
    try{
      return Provider.of<Model>(context, listen : false);
    } catch (error){
      if(!allowNull)throw error;
      return null;
    }
  }
```

**Comment by enetor** [comment] 2019-10-28 15:34
+1 to rename ProviderNotFoundError to ProviderNotFoundException.

**Comment by rrousselGit** [comment] 2019-11-26 16:36
Alright, as part of the 4.0.0, ProviderNotFoundError will be an Exception instead

This won't include an `isNull` flag though. I'm still not decided on a finite solution should be here

**Comment by rrousselGit** [comment] 2020-06-05 00:09
Closing this as `ProviderNotFound` is now an exception.

If you find it too verbose, you should be able to make your own utilities that reduce the boilerplate:

```dart
extension WachOrNull on BuildContext {
  T watchOrNull<T>() {
    try {
      return watch<T>();
    } on ProviderNotFoundException catch (err) {
     return null;
    }
  }
}
```

**Closed by rrousselGit** 2020-06-05 00:09 UTC
Labels: discussion, enhancement

**Comment by clragon** [comment] 2021-11-28 21:15
@rrousselGit 
I prefer using `Provider.of` instead of calling the methods on `context`,
but it's not possible to make an extension method `Provider.maybeOf` because extensions cant have constructors.

Could we maybe still get such a method for convinience?

**Comment by rrousselGit** [comment] 2021-11-28 21:56
@clragon such feature is no-longer necessary since version 6.0.0

You can do `Provider.of<Model?>` – in which case no `ProviderNotFoundException` will be thrown if `Model` can't be found.

**Comment by clragon** [comment] 2021-11-28 22:18
but in that case I would still have to catch said exception everytime, correct? 

Making a wrapper extension method that catches it and returns null isn't possible here.

**Comment by rrousselGit** [comment] 2021-11-28 22:46
No, as I said, no exception would be thrown. No need to catch anything
