### ISSUE TITLE
Tried to listen to a value exposed with provider, from outside of the widget tree

### ISSUE THREAD

**Issue by harsh5400** [rrousselGit/provider#313] opened 2020-01-03 17:09 UTC
I am getting this error after updating to latest version

**Comment by rrousselGit** [comment] 2020-01-03 17:19
The error message is pretty about what's the problem and what's the fix. 

What didn't you understand?

**Comment by lukasIwaszkiewicz** [comment] 2020-01-05 21:37
I would like to know why provider is outside of the widget tree? I'm getting the same error when calling provider on context of child widget.

**Comment by rrousselGit** [comment] 2020-01-05 21:43
The error message explains everything.

If there's something you do not understand, please quote it. Otherwise I don't know what you don't understand

**Comment by lukasIwaszkiewicz** [comment] 2020-01-05 21:58
`import 'package:flutter/material.dart';
import 'package:home_cloud/settings/directory-selector.dart';
import 'package:home_cloud/state/DirectorySelectionProvider.dart';
import 'package:provider/provider.dart';

class Settings extends StatefulWidget {
  final String title = 'Upload Files';

  @override
  State<StatefulWidget> createState() => _SettingsState();
}

class _SettingsState extends State<Settings> {
  List<String> selectedFolders = new List<String>();

  @override
  Widget build(BuildContext context) {

    return Provider(
      create: (context) => new DirectorySelectionProvider(),
      child: Scaffold(
        appBar: AppBar(
          title: Text('Settings'),
        ),
        body: ListView(
          children: <Widget>[
            Card(
              child: ListTile(
                leading: Icon(Icons.folder),
                title: Text('Select Directories'),
                subtitle: Text(
                    'Specify wihich directories you want to upload to cloud'),
                trailing: Icon(Icons.touch_app),
                onTap: () {
                  _showDialog();
                },
              ),
            )
          ],
        ),
      ),
    );
  }

  void _showDialog()  {


    showDialog(
      context: context,
      builder: (BuildContext context) {
        var prov = Provider.of<DirectorySelectionProvider>(context);
        return Dialog(child: DirectorySelector(prov.selectedFolders));
      },
    );
  }
}`

When I'm trying to access provider inside _showDialog I get 

>  Error: Could not find the correct Provider<DirectorySelectionProvider> above this Settings Widget

And I don't understand why. 

When I try to access it before showDialog() inside _showDialog() I get 

> Tried to listen to a value exposed with provider, from outside of the widget tree

My question is why I can't access that provider?

**Comment by rrousselGit** [comment] 2020-01-05 22:29
Read the full error message. It explains why with a code snippet similar to yours using RaisedButton.

**Comment by szeseong** [comment] 2020-01-06 08:02
@lukasIwaszkiewicz 
Here is the the widget tree from Dart DevTools.
![image](https://user-images.githubusercontent.com/438835/71803263-42fa8580-309b-11ea-9884-8baa59be681e.png)

As you can see the **Dialog** widget is different branch from the **Provider&lt;DirectorySelectionProvider&gt;** widget. 

A quick fix is to move **Provider&lt;DirectorySelectionProvider&gt;** to same branch as **Dialog** widget.

**Comment by lukasIwaszkiewicz** [comment] 2020-01-09 08:38
@szeseong that's helpful. I kind of knew I'm out of the tree but I didn't know how to check that, now I know. Thank you.

**Comment by lixia9** [comment] 2020-01-14 07:37
> The error message is pretty about what's the problem and what's the fix.
> 
> What didn't you understand?

I am getting this error after updating to latest version

 provider: ^4.0.0


[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: 'package:provider/src/provider.dart': Failed assertion: line 213 pos 7: 'context.owner.debugBuilding || listen == false || _debugIsInInheritedProviderUpdate': Tried to listen to a value exposed with provider, from outside of the widget tree.
This is likely caused by an event handler (like a button's onPressed) that called
Provider.of without passing `listen: false`.
To fix, write:
Provider.of<UserModel>(context, listen: false);
It is unsupported because may pointlessly rebuild the widget associated to the
event handler, when the widget tree doesn't care about the value.
#0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:38:5)
#2      Provider.of 
package:provider/src/provider.dart:213
#3      _SplashPageState.goPage 
package:kooflutterbase/pages/splash_page.dart:49
<asynchronous suspension>
#4      _SplashPageState.initState.<anonymous closu<…>

**Comment by rrousselGit** [comment] 2020-01-17 14:09
The fix is included in the error message. I still have trouble understanding what the problem is

**Comment by HannibalKcc** [comment] 2020-01-19 10:27
Error message is helpful.i fixed my error.

After read error message,i'm confused.
When is setting `listen: true` is the correct behavior?

Can you give an example? 
[example](https://github.com/rrousselGit/provider/blob/master/example/lib/main.dart) isn't show this case.

Thank you for your patience.

**Comment by rrousselGit** [comment] 2020-01-19 10:29
`listen: true` is the default behavior.

If you don't specify the flag, it's enabled by default

**Comment by HannibalKcc** [comment] 2020-01-19 10:45
oh,my bad.

it is confused because `provider.dart 4.0.1` 

> /// As such, it is fine to call `Provider.of` inside event handlers without
  /// specifying `listen: false`:
  ///
  /// ```dart
  /// RaisedButton(
  ///   onPressed: () {
  ///     Provider.of<Model>(context); // no need to pass listen:false
  ///
  ///     Provider.of<Model>(context, listen: false); // unnecessary flag
  ///   }
  /// )

but 4.0.2 deleted those comments.

[4.0.2 change](https://github.com/rrousselGit/provider/commit/396dcce581c3d9ca617921749ddaf65283a754bb#diff-da2d346ea0eb6c71314c09d0bf0a753dL171)

**Comment by Icyoung** [comment] 2020-01-20 03:12
4.0.2 inside onPressed or onTap  to call Provider.of must add listen: false?
Before 4.0.2, it works。
I want the reason.

**Comment by rrousselGit** [comment] 2020-01-20 07:34
It always led to a weird behavior (it made the button rebuild more often).

This is illogical and undesired, so the library now warns you against it.

**Comment by HannibalKcc** [comment] 2020-01-20 07:48
> This is illogical and undesired

`listen: true`  is the default behavior,but it's illogical.
So maybe next version(4.1.0?),`listen: false`  will be the default behavior?

**Comment by rrousselGit** [comment] 2020-01-20 08:13
`listen:true` being the default is logical.

It's not specifying `listen: false` inside an event handler that is not logical.

Also, 4.1.0 will somehow have a shorter alternative to Provider.of:

```dart
context.read<T>() // Provider.of<T>(context, listen: false)
context.watch<T>() // Provider.of<T>(context)
```

**Comment by Icyoung** [comment] 2020-01-23 03:02
ok.
extension BuildContextExtension on BuildContext {
  T read<T>() => Provider.of<T>(this, listen: false);

  T watch<T>() => Provider.of<T>(this);
}

**Comment by Icyoung** [comment] 2020-01-23 03:24
`extension BuildContextExtension on BuildContext {
  T read<T extends ChangeNotifier>() => Provider.of<T>(this, listen: false);

  T watch<T extends ChangeNotifier>() => Provider.of<T>(this);
}`

**Comment by Mirodil** [comment] 2020-01-26 02:51
Why UI not getting update when used `listen: false` but with `listen: true` it throws an error?

**Comment by Aljabri-Salman** [comment] 2020-01-28 12:08
Is there any way to access the provider from outside the widget tree ?. A common case would be using the showDialog method which navigate outside of the current tree to the root app.

**Comment by OmarBakry-eg** [comment] 2020-03-20 21:58
when I change listen to false ui screen always crash and this is error is disappear but the ui screen didn't update any more !!! it just crashing and keep crashing . now my question in provider 3 when I use provider in onPress or onTap evreything is okay now in provider 4 everything is crashing . I need an explain to how to sovle this problem

**Comment by esDotDev** [comment] 2020-03-22 21:46
In his latest talk, Remi suggests just passing the context into whatever class might need to access Provider. Unfortunately, this doesn't work well for async tasks, that outlive the page they were initiated from. As soon as the view, that held that context is pushed off stage, the context is now useless and can no longer do anything.

Think of a Logout command, that makes a service call, changes page routes to the Logout Page, and then tries to make another service call (maybe to analytics or something), it will blow up since the context originally passed in, is now expired.

This is why I still prefer to use GetIt for things that are meant to be singletons, as we just don't need to be concerned about our place in the ui tree, when accessing them.

As a workaround for provider, I will often have something like AppGlobals.rootContext, which then allows my Commands to access any of the root-level providers, in an async way, without having to screw around with which context do they get passes.

**Comment by rrousselGit** [comment] 2020-03-22 22:04
> As soon as the view, that held that context is pushed off stage, the context is now useless and can no longer do anything.

Yes, because the object is disposed of. You're not supposed to use an object after it was disposed.

If you don't want the object to be disposed, move the provider higher in the hierarchy. This is working as intended.

**Comment by esDotDev** [comment] 2020-03-22 22:22
Except I'm talking about root-level singletons, such as services. So no, this is not really working as anyone would have intended. ie, one of my pages initiates a LogoutCommand, and passes it's context to the LogoutCommand so it can access root-level services. The LogoutCommand then navigates away from that page, and tries to access another _root-level_ service, but it can't as the context it was using as lookup, is now disposed. 

There's no ability to "move things" higher in this case, the Commands are not inside the display tree, they just need a hook to access the top-level services, but that hook is no longer active.

I don't see any point in arguing about it, this is a fundamental drawback of using the display tree to lookup global services in your app, there's no point pretending it doesn't exist, or is the users fault.

**Comment by rrousselGit** [comment] 2020-03-22 22:40
> So no, this is not really working as anyone would have intended

It is. The problem is that you placed your provider in the wrong location.

Your problem is that: "one of my pages initiates a LogoutCommand"
Instead of instantiating it _inside a page_, place it above all pages. Then it won't be disposed when the route is cleared.

**Comment by esDotDev** [comment] 2020-03-22 22:46
I don't think you're understanding what I'm describing. Commands are short-lived objects that are created to do a task. So inside my view, I made have something like:
_onPressed: ()=> LogoutCommand.execute(context)_

What am I supposed to be moving up here, my button? It lives where it lives. 

This command is not getting disposed, the _context_, that it is using, to get other Provided services/models, is what is being disposed. 

To work around this, my mainView stores it's context as AppGlobals.context property, and then my commands are safe to use that, to lookup whatever they may need. 
_onPressed: ()=> LogoutCommand.execute()_

**Comment by rrousselGit** [comment] 2020-03-22 22:49
> So inside my view, I may have something like:
onPressed: ()=> LogoutCommand().execute(context)

That's a different thing indeed.

The solution would be:

```dart
onPressed: ()=> LogoutCommand().execute(context.read<Whatever>())
```

Don't pass the context to objects unrelated to Flutter/UI

**Comment by esDotDev** [comment] 2020-03-22 22:53
Sure, but that creates a load of boilerplate and parameter passing which I would definitely prefer to avoid. I don't want to be passing in 4 different things each time I run the command, when the command could just look them up itself in a lazy fashion, as needed.

**Comment by rrousselGit** [comment] 2020-03-22 22:57
Then we go back to square one, and pass the command through a provider higher in the tree:

```dart
MultiProvider(
  providers: [
    // TODO: add a bunch of providers
    Provider(create: (c) => LogoutCommand(c.read)),
  ],
  child: MyApp(),
)
```

Then instead of:

```dart
onPressed: ()=> LogoutCommand().execute(context)
```

do:

```dart
onPressed: ()=> context.read<LogoutCommand>().execute()
```

**Comment by esDotDev** [comment] 2020-03-22 23:28
No because Commands are not singletons, they are meant to be executed and then disposed. Often they are chained together, they have their own internal state, they can be dispatched concurrently, 

I may have a RefreshUsers command for example, that I kick off, and maybe it takes 1-2 seconds to complete, maybe fetches from multiple services, and updates multiple models. While that guy is finishing, I navigate away... the context he is using has now become invalidated.

There are endless use cases you can use for this sort of thing, but it just comes back to: _Anytime you need to execute an async task, outside of the display tree, it can be difficult to utilize provider as you can not rely on the context you were passed._

Your answer is basically; "Well never be outside the display list" Which is not really a solution for certain design patterns.

**Comment by esDotDev** [comment] 2020-03-22 23:36
Though, maybe something like: 
_Provider(update: (c) => LogoutCommand(c.read)),_

Would work? Returning a new command instance each time it's requested?

**Comment by rrousselGit** [comment] 2020-03-22 23:39
> Though, maybe something like:
> Provider(update: (c) => LogoutCommand(c.read)),
>
> Would work? Returning a new command instance each time it's requested? Ooh, I think I'm going to try that :)


No
But you could expose `c.read` itself:

```dart
Provider<Locator>(create: (c) => c.read)
```

Then do:

```dart
onPressed: () => LogoutCommand().execute(c.read<Locator>())
```

This is basically equivalent of using an ancestor `BuildContext` instead of the route `BuildContext`

**Comment by esDotDev** [comment] 2020-03-22 23:41
Cool, thanks for all the quick advice, I will try that out

**Comment by esDotDev** [comment] 2020-03-23 00:19
This seems is throwing an error: 
_Provider<Locator>(create: (c) => c.read)_

**error: A generic function type can't be a type argument.**

Is there any reason I couldn't just put this as the last entry in my multi-provider?
_Provider<BuildContext>(create: (c) => c)_

And then when I initiate a command, do something like:
```
var rootContext = widgetContext.read<BuildContext>()?
```

**Comment by rrousselGit** [comment] 2020-03-23 00:24
> error: A generic function type can't be a type argument.

Oh interesting. I didn't think of that one

> As an aside, is there any reason I couldn't just put this as the last entry in my top-level multi-provider?

Yeah you can

**Comment by esDotDev** [comment] 2020-03-23 00:26
Thanks Remi! This works for me. Really appreciate the help

**Comment by harshkc** [comment] 2020-03-25 10:13
I am using Provider v4.0.4 in a todo list app which lets user add,delete and checkoff tasks.
Now the problem is when onPressed is activated I am calling 
 
```
Provider.of<TaskData>(context).addTask(newTask);  
//where addTask adds the String newTask to task widget.
```
It throws an error and after going through the error it is advised to use **listen:false**.

I did the **same** and removed notifyListener() from addTask function but as thought it will not update the UI although the task widget lists update but due to listen:false it is not shown.

_What can I do to update the UI as soon the user adds the task?_

Ps: I read all the upper threads but I didn't get the clear understanding out of it. Help explaining the things will be highly appreciated.

Thank you.

**Comment by esDotDev** [comment] 2020-03-25 16:35
The code in the handler should always be non-binding (listen: false). If you want to bind for rebuilds, wrap the widget in a consumer, or just reference it in your build method:
`TaskData task = context.watch()`

setState will now be called when TaskData changes.

**Comment by nanophp** [comment] 2020-04-02 21:54
> Why UI not getting an update when used `listen: false` but with `listen: true` it throws an error?

If your widget tree let say component doesn't relate your state change operation you should use `listen = false` cause, the default behavior is true, when the value is true, it's automatically looking for widget context and then if it didn't find anything changes it gives you an error. For example, you have a widget like that, and it's clearly enough to understand that it is not a Provider context. In this case you shouldn't use `listen = true` as a default value.

```
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:your_pack_name/states/task_data.dart';

class AddTaskScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    String newTaskTitle;

    return Container(
      color: Color(0xFF757575),
      child: Container(
        padding: EdgeInsets.all(22.0),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(20.0),
            topRight: Radius.circular(20.0),
          ),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            Text(
              'Add Task',
              textAlign: TextAlign.center,
              style: TextStyle(
                color: Colors.lightBlueAccent,
                fontSize: 22.0,
              ),
            ),
            TextField(
              autofocus: true,
              autocorrect: true,
              textAlign: TextAlign.center,
              decoration: InputDecoration(
                fillColor: Colors.lightBlueAccent,
              ),
              onChanged: (String value) {
                newTaskTitle = value;
              },
            ),
            SizedBox(
              height: 20.0,
            ),
            RaisedButton(
              padding: EdgeInsets.all(20.0),
              textColor: Colors.white,
              color: Colors.lightBlueAccent,
              child: Text(
                'Add',
                style: TextStyle(
                  fontSize: 18.0,
                ),
              ),
              onPressed: () {
                Provider.of<TaskData>(
                  context,
                ).addTask(newTaskTitle);
                Navigator.pop(context);
              },
            ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by misici234** [comment] 2020-04-15 17:08
@nanophp 
This example is from Udemy course by Angela. Everything works fine with the provider
  provider: ^3.1.0+1
version specified in pub spec.yaml file when she was recording her course. The current provider package 
  provider: ^4.0.5
causes this error. Therefore, just use the old provider package.

**Comment by stromyc** [comment] 2020-04-16 13:38
> @nanophp
> This example is from Udemy course by Angela. Everything works fine with the provider
> provider: ^3.1.0+1
> version specified in pub spec.yaml file when she was recording her course. The current provider package
> provider: ^4.0.5
> causes this error. Therefore, just use the old provider package.

I'm watching the same course.

Or you could do the following:

1.  use create: instead of builder:  

return ChangeNotifierProvider<Data>(
      create: (context) {
        return Data();
      },

2.
within the callback example that Angela uses with the text field, you need to do the following:

onChanged: (newText) {
        
          Provider.of<Data>(context, listen: false).changeString(newText);
       
      },

There is a good discussion above from Remi on why we set "listen:false" vs what Angela demonstrated in the video.

**Comment by droidzone** [comment] 2020-04-19 21:08
> listen: false

If you add `listen: false`, how will you get it to rebuild the UI?

**Comment by esDotDev** [comment] 2020-04-19 21:15
You need to grab the Provided instance in your build method if you want to bind for rebuilds, as simple as that.

If you want to also fetch the instance in a button handler, and do something with it, that is a separate use case. 
```
build(){
   TaskData t = context.watch() ; //This binds you for rebuilds
   return Button(onPressed: ()=> context.read<TaskData>().doStuff(); )
```
Is the basic idea, except Remi has decided that .read() is too unsafe, so you have to use _Provider.of(listen: false)_ instead. Still think this is a really bizarre and arbitrary decision, but c'est la vie :)

**Comment by rrousselGit** [comment] 2020-04-19 21:22
I'll close this since it's more of a discussion than an actual problem

If you have any suggestion on how to improve the error message, or anything you do not understand in that message, feel free to ping me 😄

**Closed by rrousselGit** 2020-04-19 21:22 UTC
Labels: question

**Comment by HItzz07** [comment] 2020-05-01 14:10
> > This is illogical and undesired
> 
> `listen: true` is the default behavior,but it's illogical.
> So maybe next version(4.1.0?),`listen: false` will be the default behavior?

Just use the older version of the provider package, most probably 3.xx the problem seems to be solved for me.

**Comment by vinothvino42** [comment] 2020-05-05 08:13
I'm having this kind of error but my widget is in the widget tree only. I just wrapped the material app with `MultiProvider` and added `ChangeNotifierProvider` in it. But it's showing that my widget is not in the widget tree while I am accessing it in the login screen(when tapping the login button, I'm changing the auth state to authenticated, so I need to rebuild the initial widget).

**Comment by metalgurung** [comment] 2020-06-27 05:36
> > @nanophp
> > This example is from Udemy course by Angela. Everything works fine with the provider
> > provider: ^3.1.0+1
> > version specified in pub spec.yaml file when she was recording her course. The current provider package
> > provider: ^4.0.5
> > causes this error. Therefore, just use the old provider package.
> 
> I'm watching the same course.
> 
> Or you could do the following:
> 
> within the callback example that Angela uses with the RaisedButton, you need to do the following:
> 
> ```
>            onPressed: () {
>                      Provider.of<TaskData>(
>                         context, listen: false
>                         ).addTask(newTaskTitle);
>                    Navigator.pop(context);
>                }
> ```

I guess the widget got rebuild whn we clicked the keyboard check button, and let to clear the value of String, convert the Class to stateless to Preserve the String value which worked for me.

**Comment by Sandeep-peddi** [comment] 2020-08-31 12:39
> > > @nanophp
> > > This example is from Udemy course by Angela. Everything works fine with the provider
> > > provider: ^3.1.0+1
> > > version specified in pub spec.yaml file when she was recording her course. The current provider package
> > > provider: ^4.0.5
> > > causes this error. Therefore, just use the old provider package.
> > 
> > 
> > I'm watching the same course.
> > Or you could do the following:
> > within the callback example that Angela uses with the RaisedButton, you need to do the following:
> > ```
> >            onPressed: () {
> >                      Provider.of<TaskData>(
> >                         context, listen: false
> >                         ).addTask(newTaskTitle);
> >                    Navigator.pop(context);
> >                }
> > ```
> 
> I guess the widget got rebuild whn we clicked the keyboard check button, and led to clear the value of String var, convert the Class to stateless to Preserve the String value which worked for me.

listen false is not working. Actually in previous version (for Angela) listen is true by default, in latter versions it removed as it is taking high performance
The value of newTaskTitle is not updating with the value of TextFeild. and as it is returning null value to the text of taskTile, it is giving error. Is there any other option, everything else is workihng fine. When am giving a a value to newTaskTitle initially when it is declared, it is working fine

**Comment by Jinxishihenian** [comment] 2020-09-01 03:28
> I am getting this error after updating to latest version

Please read in detaill  https://flutter.cn/docs/development/data-and-backend/state-mgmt/simple

**Comment by edpchinthana** [comment] 2020-09-03 02:32
Hello, This may be a stupid question. I want to change the state from outside widget tree. Is it possible? When I use `listen: false` it does not affect the state. Does anyone have a suggestion for this? This might irrelevant to this git issue. Sorry

**Comment by esDotDev** [comment] 2020-09-03 02:55
The state probably changed, but the view is not bound? 

```
void handleClick() => context.read<Foo>().bar = "changed";

build(c) {
   Foo foo = context.watch();//Don't forget to bind
   return Text(foo.bar);
}
```

**Comment by edpchinthana** [comment] 2020-09-03 03:08
I want to load data from the shared preference to state if the user is logged in. I placed the code for getting data from shared preference in the app state and put notifyListeners(). I wanted to call this function from the init state on a loading screen. `context.read<AppState>().setCounter();` I tried to like this. but it doesn't notify listeners. It looks like another instance of the state. I am a beginner. That's what I understood. Do you guys have a suggestion to archive this task?

**Comment by Mickey-A-Mouse** [comment] 2020-10-20 17:54
I think the better solution is to check this whether your user is logged in or not from inside of provider, and then depends on that provider you should do whatever you want)) Just put your provider on top of widget tree!)) Hope it helps!)

**Comment by mikkyboy2005** [comment] 2020-11-02 19:35
> I am getting this error after updating to latest version

add (context, listen: false) whenever you call the data from the provider

example below:

Provider.of<TaskData>(context, listen: false).addTask(newTaskTitle.toString());

**Comment by 4limsyed** [comment] 2020-11-28 21:33
due to the new provider update you need to use something like this. 

\\
context.read<Counter>().increment(),
\\

**Comment by Mayank-ck2mk** [comment] 2021-02-25 18:30
```
To fix, write:
Provider.of<TaskData>(context, listen: false);

It is unsupported because may pointlessly rebuild the widget associated to the
event handler, when the widget tree doesn't care about the value.
```

I am facing difficulty in understanding this fix, can anyone please help me understand it more clearly?

Why we necessarily need _listen: false_ in this case and why does it gives an error when we use the default _listen: true_

**Comment by cheenbee** [comment] 2021-04-07 08:19
> ```
> To fix, write:
> Provider.of<TaskData>(context, listen: false);
> 
> It is unsupported because may pointlessly rebuild the widget associated to the
> event handler, when the widget tree doesn't care about the value.
> ```
> 
> I am facing difficulty in understanding this fix, can anyone please help me understand it more clearly?
> 
> Why we necessarily need _listen: false_ in this case and why does it gives an error when we use the default _listen: true_
         
         flutter sample provider_counter :

          You can access your providers anywhere you have access
          to the context. One way is to use Provider.of<Counter>(context).

          The provider package also defines extension methods on context
          itself. You can call context.watch<Counter>() in a build method
          of any widget to access the current state of Counter, and to ask
          Flutter to rebuild your widget anytime Counter changes.

          You can't use context.watch() outside build methods, because that
          often leads to subtle bugs. Instead, you should use
          context.read<Counter>(), which gets the current state
          but doesn't ask Flutter for future rebuilds.

          Since we're in a callback that will be called whenever the user
          taps the FloatingActionButton, we are not in the build method here.
          We should use context.read().

**Comment by akshatjain2k** [comment] 2021-05-04 14:32
Error: The method 'read' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'read'.
              context.read()<AuthenticationService>().signIn(


how to define read in this code ?
code:

import 'package:firebaselogin/authentication_service.dart';
import 'package:flutter/material.dart';

class SignInPage extends StatelessWidget {
  final TextEditingController emailController = TextEditingController();
  final TextEditingController passwordController = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          TextField(
            controller: emailController,
            decoration: InputDecoration(
                labelText: "Email", hintText: "Type Email here"),
          ),
          TextField(
            controller: passwordController,
            decoration: InputDecoration(
                labelText: "Password", hintText: "Type Password here"),
          ),
          RaisedButton(
            onPressed: () {
              context.read()<AuthenticationService>().signIn(
                  email: emailController.text.trim(),
                  password: passwordController.text.trim());
            },
            child: Text("Sign in"),
          )
        ],
      ),
    );
  }
}

**Comment by sheng-di** [comment] 2024-04-07 15:34
> The error message explains what's the problem and what's the fix.
> 
> What didn't you understand?

So what't the conclusion? How can we get the LATEST value? Adding `listen:  #false` cannot get the latest value. I have to click button twice to get the latest value at the second time.
