### ISSUE TITLE
returns null on consumer

### ISSUE THREAD

**Issue by Raviteja11122** [rrousselGit/provider#327] opened 2020-01-24 08:38 UTC
provider_setup.dart

```
import 'package:document_saver/core/enum/connectivity_status.dart';
import 'package:document_saver/core/models/screen.dart';
import 'package:document_saver/core/services/api.dart';
import 'package:document_saver/core/services/connection_service.dart';
import 'package:document_saver/core/services/screen_util_service.dart';
import 'package:document_saver/core/services/user_service.dart';
import 'package:flutter_login_package/models/user.dart';
import 'package:provider/single_child_widget.dart';
import 'package:provider/provider.dart';

List<SingleChildWidget> multiProviders = [
  ...independentServices,
  ...dependentServices,
  ...uiConsumables
];

List<SingleChildWidget> independentServices = [
  Provider.value(value: Api()),
  Provider.value(value: UserService()),
  Provider.value(value: ConnectivityService()),
  Provider.value(value: ScreenUtilService())
];

List<SingleChildWidget> dependentServices = [
];

List<SingleChildWidget> uiConsumables = [
  StreamProvider<User>(
    create: (context) => Provider.of<UserService>(context, listen: false).user,
  ),
  StreamProvider<ConnectivityStatus>(
    create: (context) => Provider.of<ConnectivityService>(context, listen: false).connectionStatusStream,
  ),
  StreamProvider<Screen>(
    create: (context) => Provider.of<ScreenUtilService>(context, listen: false).screen,
  ),
];
```
homepage.dart

```
return ChangeNotifierProvider<DocumentViewModel>(
      model: DocumentViewModel(api: Provider.of(context), screenUtilService: Provider.of(context), user: Provider.of<User>(context)),
      child: Consumer<DocumentViewModel>(
        builder: (context, model, child) {
        print(Provider.of<User>(context).internalId);
        return SingleChildScrollView(
          child: Column(
            children: <Widget>[
              BuildCategories(loginId: Provider.of<User>(context, listen: false).internalId, isFamilyMem: false),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 20.0),
                child: Divider(color: Colors.grey),
              ),
              CommunicationWidget(),
              BuildServices(data: {"loginId": Provider.of<User>(context, listen: false).internalId, "isFamilyMem": false}),
            ],
          ),
        );

      }
      )
    );
```

multiProviders passed in main.dart
in homepage getting null with exception thrown when I printing this Provider.of<User>(context).internalId
what I'm missing

**Comment by Raviteja11122** [comment] 2020-01-24 10:14
I added lazy to false to stream provider it solves my error is that good to use??

**Comment by rrousselGit** [comment] 2020-01-25 18:53
I don't really understand your code snippet.

`ChangeNotifierProvider` doesn't have a `model` parameter.

**Comment by Raviteja11122** [comment] 2020-01-26 07:26
@rrousselGit 
I'm using another dart file for changeNotifierProvider and used that widget to make it easier to understand for you. I changed code
This is my other file

```
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class BaseWidget<T extends ChangeNotifier> extends StatefulWidget {
  final Widget Function(BuildContext context, T model, Widget child) builder;
  final T model;
  final Widget child;
  final Function(T) onModelReady;

  BaseWidget({
    Key key,
    this.builder,
    this.model,
    this.child,
    this.onModelReady,
  }) : super(key: key);

  _BaseWidgetState<T> createState() => _BaseWidgetState<T>();
}

class _BaseWidgetState<T extends ChangeNotifier> extends State<BaseWidget<T>> {
  T model;

  @override
  void initState() {
    model = widget.model;

    if (widget.onModelReady != null) {
      widget.onModelReady(model);
    }

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<T>(
      create: (context) => model,
      child: Consumer<T>(
        builder: widget.builder,
        child: widget.child,
      ),
    );
  }
}
```

and this is the actual code

```
Widget build(BuildContext context) {

    return BaseWidget<DocumentViewModel>(
      model: DocumentViewModel(api: Provider.of(context), screenUtilService: Provider.of(context), user: Provider.of<User>(context, listen: false)),
      onModelReady: (model) => model.getDocuments(Provider.of<ConnectivityStatus>(context)),
      builder: (context, model, child) {
        model.setScreenUtil(context);
        print(Provider.of<User>(context, listen: false).internalId);
        return SingleChildScrollView(
          child: Column(
            children: <Widget>[
              BuildCategories(loginId: model.user.internalId, isFamilyMem: false),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 20.0),
                child: Divider(color: Colors.grey),
              ),
              CommunicationWidget(),
              BuildServices(data: {"loginId": model.user.internalId, "isFamilyMem": false}),
            ],
          ),
        );
      }
    );
  }
```

**Comment by rrousselGit** [comment] 2020-06-04 23:48
Considering the issue is old and without answer, I'll close this for now.

If you still have problem, feel free to say so!

**Closed by rrousselGit** 2020-06-04 23:48 UTC
Labels: question
